// The journey maps — one mermaid flowchart per member, written to docs/members/maps.md from the
// journey files plus the run's results. docs/PICTURES.md's grammar for a colourblind reader: the
// member's path is the THICK edge (`==>`), a dead end is a CROSS-HEAD (`--x`) into a node that
// names it, and the route graph is plain boxes — no hue carries meaning. Node budget: 15 per map
// (the legibility budget PICTURES.md points at); routes beyond it fold into "… n more".
//
// Generated, never hand-edited: `npm run mermaid:lint docs/members/maps.md` is the gate.

import { writeFileSync } from "node:fs";

const MAX_NODES = 15;

const routeLabel = (goto) => {
  const u = new URL(goto, "http://x");
  const section = u.searchParams.get("section");
  const base = u.pathname.replace(/^\/app\/?/, "/") || "/";
  return section ? `${base} · ${section}` : base;
};

/** Every route a member visits, in first-seen order, capped. */
function routesOf(member) {
  const seen = [];
  for (const j of member.journeys) {
    for (const s of j.steps) {
      const label = routeLabel(s.goto);
      if (!seen.includes(label)) seen.push(label);
    }
  }
  return seen;
}

/**
 * @param {object} member  a parsed journey file
 * @param {Map<string, boolean>} fixed  step key → "its known gap passed" (drawn dotted, not crossed)
 */
export function mapFor(member, fixed = new Map()) {
  const routes = routesOf(member);
  const deadEnds = [];
  for (const j of member.journeys) {
    for (const s of j.steps) {
      if (s.known_gap) deadEnds.push({ from: routeLabel(s.goto), step: `${j.id}-${s.id}`, s });
    }
  }
  // Budget: routes first, then as many dead ends as fit; the rest are counted, not drawn.
  const routeBudget = Math.max(3, MAX_NODES - Math.min(deadEnds.length, 6));
  const drawnRoutes = routes.slice(0, routeBudget);
  const hiddenRoutes = routes.length - drawnRoutes.length;
  const deadBudget = MAX_NODES - drawnRoutes.length - (hiddenRoutes ? 1 : 0);
  const drawnDead = deadEnds.filter((d) => drawnRoutes.includes(d.from)).slice(0, deadBudget);

  const id = (label) => `r${drawnRoutes.indexOf(label)}`;
  const lines = ["flowchart LR"];
  for (const r of drawnRoutes) lines.push(`  ${id(r)}["${r}"]`);
  if (hiddenRoutes) lines.push(`  more["… ${hiddenRoutes} more routes"]`);
  const edges = new Set();
  for (const j of member.journeys) {
    let prev;
    for (const s of j.steps) {
      const here = routeLabel(s.goto);
      if (!drawnRoutes.includes(here)) continue;
      if (prev !== undefined && prev !== here) edges.add(`  ${id(prev)} ==> ${id(here)}`);
      prev = here;
    }
  }
  for (const e of edges) lines.push(e);
  drawnDead.forEach((d, i) => {
    const tag = d.s.known_gap.match(/dead end \d/)?.[0] ?? "gap";
    const short = d.s.known_gap
      .replace(/^dead end \d\s*[—–-]\s*/, "")
      .split(/[(;]/)[0]
      .trim();
    const cut = short.length > 48 ? `${short.slice(0, 48).replace(/\s+\S*$/, "")}…` : short;
    const label = `${tag}: ${cut}`;
    const arrow = fixed.get(`${member.member}/${d.step}`) ? "-.->" : "--x";
    lines.push(`  ${id(d.from)} ${arrow} d${i}["${label.replace(/"/g, "'")}"]`);
  });
  return lines.join("\n");
}

export function writeMaps(path, members, run) {
  const fixed = new Map(run.fixed ?? []);
  const out = [
    "# Journey maps — one per member",
    "",
    `_Generated by \`scripts/crawl/run.mjs\` from \`e2e/journeys/*.journey.json\` and run ${run.date}. The member's path is the thick edge; a cross-head is a dead end the journey file names as a known gap (a dotted edge means the gap passed this run — remove its \`known_gap\`). Route graph only; the eight dead ends' text lives in \`friction-ledger.md\`._`,
    "",
  ];
  for (const m of members) {
    out.push(`## ${m.member}`, "", "```mermaid", mapFor(m, fixed), "```", "");
    out.push(
      `_${m.journeys.length} journey${m.journeys.length === 1 ? "" : "s"}: ${m.journeys.map((j) => j.name).join(" · ")}. Source: \`${m.source}\`._`,
      "",
    );
  }
  writeFileSync(path, out.join("\n"));
}
