// ASSIGNMENTS — #3818 slice 5 (#4289): send Eric only decisions, as GitHub assignments.
//
// WHY ASSIGNMENTS. Every ask used to post under `ejclark`, and GitHub never notifies you of your
// own posts — so nothing came back to him (#3818's call 2: 0 call sites assigned him; 8 open
// `needs-eric`, median ~15.5 days). An assignment by a bot DOES push to GitHub Mobile.
//
// THE DRY RUN CAME FIRST, AND IT IS STILL THE CLI DEFAULT. Assigning is a GitHub write on Eric's
// own queue, so the plan's rule was "dry run for one day first". Two dry runs are on #4289's thread
// — 2026-10-01 (1 would-be assignment) and 2026-10-02 (2) — both tiny and both correct, which is the
// reading that rule existed to produce. So this file now has a write path, behind `--apply`;
// `--dry-run` remains what you get by default and what the report is for.
//
// WHY THE PUSH SWEEP, NOT A WORKFLOW STEP. #4289's own note planned the live half as a
// `.github/**` platter item — an envelope-protected file, so one more merge of Eric's. It does not
// need to be: the sweep already runs `index.mjs` on every push with the App token, so this lane
// folds in beside the relay (slice 4) as a routed intent and costs him nothing. Same outcome, one
// fewer touch point, which is this whole plan's point.
//
// THE BLAST-RADIUS BOUND IS `ASSIGN_CAP`. A live lane that reads the queue wrong could assign Eric
// to everything it can see once. Three new assignments per tick means a wrong read costs three
// notifications and three `unassign`s, not a queue-wide fan-out — the same instinct as the relay's
// watermark (#4484) and the receipt sweep's batch cap. Removals are uncapped: they only ever shrink
// his queue, and holding one back would leave a stale assignment pushing at him.
//
// WHAT IT PLANS (#3818's EARS criteria):
//   1. `needs-eric` + a `Needs from you` line → assign ejclark, one comment quoting the line.
//   2. label removed / issue closed → remove only the assignments this lane made (its marker).
//   3. never a second assignment comment on one issue — the marker is the memory.
//   4. a held or platter PR unmerged ≥12h → assign ejclark.
// And the HONEST QUEUE half: every open `needs-eric` with the one decision it waits on, flagging the
// ones that state none — `needs-eric` means exactly one thing, a decision only Eric can make
// (CLAUDE.md), so a label with no stated decision is a candidate to clear, never an assignment.
//
// #4293 (digest criterion 12): `plan()` also returns `needsYou` — the set Eric holds once this run's
// writes land — and `digest-scan.mjs --needs-you` prints exactly that list. One selector, two
// readers; tests/scripts/moneypenny/needs-you.spec.ts fails if they ever disagree.
import { aboveFold } from "../issue-lint.mjs";
import { ERIC, NEEDS_ERIC } from "./decision-callout.mjs";
import { ghRestAll, sh, withRetry } from "./gh.mjs";

export const ASSIGN_MARKER = "<!-- moneypenny:assigned -->";
export const HOLD_MERGE = "hold-merge";
export const HELD_PR_HOURS = 12;
/** New assignments one sweep tick may make. See the header: the bound on a wrong read. */
export const ASSIGN_CAP = 3;

const names = (labels = []) => labels.map((l) => (typeof l === "string" ? l : l?.name));
const logins = (users = []) => users.map((u) => (typeof u === "string" ? u : u?.login));
const isEric = (login) => String(login ?? "").toLowerCase() === ERIC;

/**
 * The one decision an issue waits on: the first numbered item of its `> [!IMPORTANT]` / `Needs
 * from you` callout above the fold, else the first plain callout line after the heading. `null`
 * when there is no callout — the "no stated decision" case. Pure.
 */
export function decisionLine(body = "") {
  const lines = aboveFold(body ?? "").split("\n");
  const start = lines.findIndex((l) => /^>\s*\[!IMPORTANT\]/.test(l));
  if (start === -1) return null;
  const callout = [];
  for (const l of lines.slice(start + 1)) {
    if (!/^>/.test(l)) break;
    callout.push(l.replace(/^>\s?/, "").trim());
  }
  const head = callout.findIndex((l) => /needs from you/i.test(l));
  if (head === -1) return null;
  const rest = callout.slice(head + 1).filter(Boolean);
  const numbered = rest.find((l) => /^\d+\.\s+/.test(l));
  const pick = numbered ?? rest[0];
  return pick ? pick.replace(/^(\d+\.|[-*])\s+/, "") : null;
}

/** The comment criterion 1 posts: the decision quoted, the marker that makes criteria 2–3 work. */
export function assignmentComment({ decision }) {
  return [
    `@${ERIC} — assigned to you for one decision:`,
    "",
    `> ${decision}`,
    "",
    "Reply here in a word; this lane removes the assignment when the label comes off or the issue closes.",
    "",
    ASSIGN_MARKER,
    "",
    "---",
    "_Generated by [Claude Code](https://claude.ai/code)_",
  ].join("\n");
}

/**
 * Plan every action, write nothing. Inputs are REST shapes (labels/assignees as objects or
 * strings); `markers` is the set of issue/PR numbers already carrying this lane's marker comment.
 * Returns `{ queue, actions, needsYou }`: `queue` is the honest-queue listing, `actions` the
 * would-be writes, each with the criterion and a one-line why, and `needsYou` the set Eric holds
 * once those writes land (criterion 12 — the digest's Needs-you list). Pure.
 */
export function plan({ issues = [], prs = [], markers = new Set(), now = Date.now() } = {}) {
  const queue = [];
  const actions = [];
  const needsYou = [];
  const ask = (row) => needsYou.some((n) => n.number === row.number) || needsYou.push(row);
  // CRITERION 4 OUTRANKS CRITERION 2 ON THE SAME NUMBER, and this set is what makes that true.
  // GitHub lists a PR among `issues`, so a PR assigned under criterion 4 reaches `planIssue` as an
  // issue that is marked, assigned and has no `needs-eric` — which reads as "the label came off,
  // clear it". The first live run (2026-10-02, #4436) assigned the held PR and the next tick wanted
  // to unassign it: an assign/unassign loop pushing at Eric twice per cycle. Computed before either
  // loop, because the issue pass runs first (its results are what dedupes criterion 4's own ask).
  const stillHeld = new Set(
    prs.filter((pr) => heldPrHours(pr, now) !== null).map((pr) => pr.number),
  );
  for (const issue of issues) planIssue(issue, { markers, now, queue, actions, ask, stillHeld });
  for (const pr of prs) {
    const hours = heldPrHours(pr, now);
    if (hours === null) continue;
    const why = `held PR unmerged ${Math.floor(hours)}h (≥${HELD_PR_HOURS}h)`;
    ask({ number: pr.number, title: pr.title, criterion: 4, why });
    if (actions.some((a) => a.kind === "assign" && a.number === pr.number)) continue; // one ask each
    // `!markers.has` is criterion 3 applied to criterion 4, and it is load-bearing, not symmetry.
    // Without it: Eric unassigns himself from a still-held PR, which drops it out of `gather()`'s
    // issue reads (no `needs-eric`, no longer assigned to him) so nothing else can see it — and
    // every later push re-assigns him and posts another marker comment, forever, with `stillHeld`
    // blocking criterion 2 from ever clearing it. Marked means asked; an unassign after that is his
    // answer.
    if (!(markers.has(pr.number) || logins(pr.assignees).some(isEric))) {
      actions.push({
        kind: "assign",
        criterion: 4,
        number: pr.number,
        title: pr.title,
        why,
        // A held PR carries no callout, so name the one thing that IS known: it is held, and a held
        // PR only moves on his click. Deliberately does NOT claim green or protected — `heldPrHours`
        // reads state, draft, label and age and nothing else, and `hold-merge` also goes on a PR
        // held for a taste fork, so either word would be the app telling him something it never
        // checked.
        decision: `Merge this held PR, or say what it's waiting on — it has been open and held ${Math.floor(hours)}h, and a held PR moves only on your click.`,
      });
    }
  }
  return { queue, actions, needsYou };
}

/** Criteria 1–3 and the honest queue, for one issue (or a PR GitHub lists as one). */
function planIssue(issue, { markers, now, queue, actions, ask, stillHeld = new Set() }) {
  const assigned = logins(issue.assignees).some(isEric);
  const marked = markers.has(issue.number);
  const open = (issue.state ?? "open") === "open";
  const act = (kind, criterion, why) =>
    actions.push({ kind, criterion, number: issue.number, title: issue.title, why });

  if (!(open && names(issue.labels).includes(NEEDS_ERIC))) {
    if (marked && assigned && !stillHeld.has(issue.number)) {
      act("unassign", 2, open ? "needs-eric removed" : "issue closed");
    }
    return;
  }
  const decision = decisionLine(issue.body);
  queue.push({
    number: issue.number,
    title: issue.title,
    decision,
    author: issue.user?.login ?? "",
    assigned,
    ageDays: Math.floor((now - Date.parse(issue.created_at ?? now)) / 864e5),
  });
  // No stated decision → a clear candidate, never an ask. Marked → criterion 3, asked once
  // already. Assigned → his by hand; nothing to add.
  const why = `needs-eric with a stated decision: "${decision}"`;
  if (decision && !marked && !assigned) {
    actions.push({
      kind: "assign",
      criterion: 1,
      number: issue.number,
      title: issue.title,
      why,
      decision,
    });
  }
  // Needs-you = what he holds after this run: stated, and either his already or about to be. A
  // marked issue he unassigned himself stays off — criterion 3 means the lane won't re-ask.
  if (decision && (assigned || !marked)) {
    ask({ number: issue.number, title: issue.title, criterion: 1, why, decision });
  }
}

/** Criterion 4's test for one PR: held (`hold-merge` or `platter/`), open, ready, ≥12h → hours. */
function heldPrHours(pr, now) {
  if ((pr.state ?? "open") !== "open" || pr.draft) return null;
  const held = names(pr.labels).includes(HOLD_MERGE) || /^platter\//.test(pr.head?.ref ?? "");
  if (!held) return null;
  const hours = (now - Date.parse(pr.created_at ?? now)) / 36e5;
  return hours < HELD_PR_HOURS ? null : hours;
}

/** The dry run's report, as markdown — what Eric reads before anything is switched on. Pure. */
export function report({ queue, actions }) {
  const out = ["## Honest queue — open `needs-eric`", ""];
  if (!queue.length) out.push("_none_");
  else {
    out.push("| # | Waits on | Age | Assigned | Verdict |", "|---|---|---|---|---|");
    for (const q of queue) {
      const verdict = q.decision ? "keep" : "**clear candidate** — no stated decision";
      const waits = q.decision ? q.decision.replaceAll("|", "\\|") : "—";
      out.push(
        `| #${q.number} | ${waits} | ${q.ageDays}d | ${q.assigned ? "yes" : "no"} | ${verdict} |`,
      );
    }
  }
  const clear = queue.filter((q) => !q.decision).length;
  out.push("", `${queue.length} open · ${clear} with no stated decision (listed, not cleared).`);
  out.push("", "## Would do (dry run — nothing written)", "");
  if (!actions.length) out.push("_nothing_");
  for (const a of actions)
    out.push(`- **${a.kind}** #${a.number} (criterion ${a.criterion}) — ${a.why}`);
  return out.join("\n");
}

/**
 * The sweep's view of `plan()`: `plan`'s actions as intents `index.mjs` can execute, capped.
 *
 * Pure, and a no-op without `deps.assignments` — every non-push event and every `routeSweep`
 * fixture that predates this lane therefore routes exactly as it did before.
 *
 * Removals go first and are never capped (criterion 2: a stale assignment is still pushing at him),
 * then at most `ASSIGN_CAP` new asks by ascending number — oldest first, because REST hands back
 * `labels=` newest-first and a cap applied to that order would starve the items that have waited
 * longest, which is exactly the 15.5-day median this plan set out to fix.
 *
 * @param deps { assignments: { issues, prs, markers }, now }
 * @returns Intent[] — `[]` on most pushes, which is the correct answer.
 */
export function routeAssignments(deps = {}) {
  const { assignments, now = Date.now() } = deps;
  if (!assignments) return [];
  const { actions } = plan({ ...assignments, now });
  const removals = actions.filter((a) => a.kind === "unassign");
  const asks = actions.filter((a) => a.kind === "assign").sort((a, b) => a.number - b.number);
  const batch = asks.slice(0, ASSIGN_CAP);
  if (asks.length > batch.length) {
    // stderr only — stdout carries machine-read output on some call paths of this router.
    console.error(
      `::notice::assignments — asking Eric about ${batch.length} of ${asks.length} item(s) this ` +
        `tick (cap ${ASSIGN_CAP}); the rest follow on later pushes.`,
    );
  }
  return [...removals, ...batch].map((a) => ({
    kind: a.kind === "assign" ? "assign-eric" : "unassign-eric",
    number: a.number,
    title: a.title,
    criterion: a.criterion,
    why: a.why,
    body: a.kind === "assign" ? assignmentComment({ decision: a.decision }) : undefined,
  }));
}

/**
 * Carry out one assignment intent. THE ASSIGNMENT GOES FIRST, and which order is a real choice.
 *
 * Two writes cannot be atomic, so one can land alone — so pick the order whose half-write is the
 * recoverable one, and the marker comment is what decides that. The marker IS this lane's memory
 * (criteria 2 and 3), so:
 *   - comment first, assign fails → the issue is marked, so criterion 1 never asks again AND
 *     `needsYou` drops it (`decision && (assigned || !marked)`). The decision disappears from the
 *     assignment channel and from `digest-scan --needs-you` at once. Unrecoverable and silent.
 *   - assign first, comment fails → Eric holds the assignment, so the phone push (the entire point)
 *     landed and the digest still lists it; only the convenience quote is missing, and the issue's
 *     own `Needs from you` callout is the real copy anyway.
 * The second is strictly the better failure, so: assign, then comment. Both writes are retried for
 * GitHub's own 5xx, which is the overwhelmingly likely cause of a single-write failure.
 *
 * `gh api`, not `gh issue edit`/`gh issue comment`: criterion 4's targets are PRs, and the issue
 * subcommands refuse a PR number while the `issues/` REST route serves both.
 */
export function executeAssignments(intent, { run = sh, retry = withRetry } = {}) {
  const n = String(intent.number);
  const assignees = (method) =>
    retry(() =>
      run("gh", [
        "api",
        "--method",
        method,
        `repos/{owner}/{repo}/issues/${n}/assignees`,
        "-f",
        `assignees[]=${ERIC}`,
      ]),
    );
  if (intent.kind === "unassign-eric") {
    assignees("DELETE");
    return `🧹 unassigned #${n} — ${intent.why}`;
  }
  assignees("POST");
  retry(() =>
    run("gh", [
      "api",
      "--method",
      "POST",
      `repos/{owner}/{repo}/issues/${n}/comments`,
      "-f",
      `body=${intent.body}`,
    ]),
  );
  return `📬 assigned #${n} to @${ERIC} (criterion ${intent.criterion}) — ${intent.why}`;
}

/** The live REST read both the dry run and the digest plan from — one gather, one `plan()`. */
export function gather() {
  // PRs stay in: a held PR can carry `needs-eric` too (#4361), and GitHub lists it as an issue.
  const issues = ghRestAll(`issues?state=open&labels=${NEEDS_ERIC}`);
  // Criterion 2's candidates: things Eric holds that may have lost the label or closed since.
  const seen = new Set(issues.map((i) => i.number));
  const since = new Date(Date.now() - 14 * 864e5).toISOString();
  for (const i of ghRestAll(`issues?state=all&assignee=${ERIC}&since=${since}`)) {
    if (!seen.has(i.number)) issues.push(i);
  }
  const prs = ghRestAll("pulls?state=open");
  // Marker candidates: every issue above, PLUS the held PRs criterion 4 targets. The PRs matter —
  // without their markers, a PR Eric unassigned himself from is invisible to every other read here
  // and gets re-asked on every push (see `plan`'s `!markers.has(pr.number)`). Only the ones already
  // past the hold window, so this is normally one or two extra reads, not one per open PR.
  const candidates = new Set(issues.map((i) => i.number));
  for (const pr of prs) if (heldPrHours(pr, Date.now()) !== null) candidates.add(pr.number);
  const markers = new Set();
  for (const n of candidates) {
    const comments = ghRestAll(`issues/${n}/comments`);
    if (comments.some((c) => (c.body ?? "").includes(ASSIGN_MARKER))) markers.add(n);
  }
  return { issues, prs, markers };
}

function main(argv) {
  const apply = argv.includes("--apply");
  const deps = gather();
  const planned = plan(deps);
  if (!apply) {
    console.log(argv.includes("--json") ? JSON.stringify(planned, null, 2) : report(planned));
    if (planned.actions.length) console.log("\nRun again with --apply to write them.");
    return;
  }
  // By hand, the same path the push sweep takes — one route, never a second that can drift.
  const intents = routeAssignments({ assignments: deps });
  if (!intents.length) {
    console.log("· nothing to assign or clear");
    return;
  }
  for (const i of intents) console.log(executeAssignments(i));
}

if (import.meta.url === `file://${process.argv[1]}`) main(process.argv.slice(2));
