// ASSIGNMENTS — #3818 slice 5 (#4289): send Eric only decisions, as GitHub assignments.
//
// WHY ASSIGNMENTS. Every ask used to post under `ejclark`, and GitHub never notifies you of your
// own posts — so nothing came back to him (#3818's call 2: 0 call sites assigned him; 8 open
// `needs-eric`, median ~15.5 days). An assignment by a bot DOES push to GitHub Mobile.
//
// WHY DRY-RUN ONLY (this PR). Assigning is a GitHub write on Eric's own queue. The plan's rule is
// "dry run for one day first": he reads what WOULD be assigned, and only then does a separate,
// explicit step switch writes on. So this file has no write path at all — `--dry-run` is required
// and the CLI refuses without it. The workflow wiring is `.github/**` (the envelope) and is a
// follow-up on #4289, not this PR.
//
// WHAT IT PLANS (#3818's EARS criteria):
//   1. `needs-eric` + a `Needs from you` line → assign ejclark, one comment quoting the line.
//   2. label removed / issue closed → remove only the assignments this lane made (its marker).
//   3. never a second assignment comment on one issue — the marker is the memory.
//   4. a held or platter PR unmerged ≥12h → assign ejclark.
// And the HONEST QUEUE half: every open `needs-eric` with the one decision it waits on, flagging the
// ones that state none — `needs-eric` means exactly one thing, a decision only Eric can make
// (CLAUDE.md), so a label with no stated decision is a candidate to clear, never an assignment.
//
// #4293 (digest criterion 12): `plan()` also returns `needsYou` — the set Eric holds once this run's
// writes land — and `digest-scan.mjs --needs-you` prints exactly that list. One selector, two
// readers; tests/scripts/moneypenny/needs-you.spec.ts fails if they ever disagree.
import { aboveFold } from "../issue-lint.mjs";
import { ERIC, NEEDS_ERIC } from "./decision-callout.mjs";
import { ghRestAll } from "./gh.mjs";

export const ASSIGN_MARKER = "<!-- moneypenny:assigned -->";
export const HOLD_MERGE = "hold-merge";
export const HELD_PR_HOURS = 12;

const names = (labels = []) => labels.map((l) => (typeof l === "string" ? l : l?.name));
const logins = (users = []) => users.map((u) => (typeof u === "string" ? u : u?.login));
const isEric = (login) => String(login ?? "").toLowerCase() === ERIC;

/**
 * The one decision an issue waits on: the first numbered item of its `> [!IMPORTANT]` / `Needs
 * from you` callout above the fold, else the first plain callout line after the heading. `null`
 * when there is no callout — the "no stated decision" case. Pure.
 */
export function decisionLine(body = "") {
  const lines = aboveFold(body ?? "").split("\n");
  const start = lines.findIndex((l) => /^>\s*\[!IMPORTANT\]/.test(l));
  if (start === -1) return null;
  const callout = [];
  for (const l of lines.slice(start + 1)) {
    if (!/^>/.test(l)) break;
    callout.push(l.replace(/^>\s?/, "").trim());
  }
  const head = callout.findIndex((l) => /needs from you/i.test(l));
  if (head === -1) return null;
  const rest = callout.slice(head + 1).filter(Boolean);
  const numbered = rest.find((l) => /^\d+\.\s+/.test(l));
  const pick = numbered ?? rest[0];
  return pick ? pick.replace(/^(\d+\.|[-*])\s+/, "") : null;
}

/** The comment criterion 1 posts: the decision quoted, the marker that makes criteria 2–3 work. */
export function assignmentComment({ decision }) {
  return [
    `@${ERIC} — assigned to you for one decision:`,
    "",
    `> ${decision}`,
    "",
    "Reply here in a word; this lane removes the assignment when the label comes off or the issue closes.",
    "",
    ASSIGN_MARKER,
    "",
    "---",
    "_Generated by [Claude Code](https://claude.ai/code)_",
  ].join("\n");
}

/**
 * Plan every action, write nothing. Inputs are REST shapes (labels/assignees as objects or
 * strings); `markers` is the set of issue/PR numbers already carrying this lane's marker comment.
 * Returns `{ queue, actions, needsYou }`: `queue` is the honest-queue listing, `actions` the
 * would-be writes, each with the criterion and a one-line why, and `needsYou` the set Eric holds
 * once those writes land (criterion 12 — the digest's Needs-you list). Pure.
 */
export function plan({ issues = [], prs = [], markers = new Set(), now = Date.now() } = {}) {
  const queue = [];
  const actions = [];
  const needsYou = [];
  const ask = (row) => needsYou.some((n) => n.number === row.number) || needsYou.push(row);
  for (const issue of issues) planIssue(issue, { markers, now, queue, actions, ask });
  for (const pr of prs) {
    const hours = heldPrHours(pr, now);
    if (hours === null) continue;
    const why = `held PR unmerged ${Math.floor(hours)}h (≥${HELD_PR_HOURS}h)`;
    ask({ number: pr.number, title: pr.title, criterion: 4, why });
    if (actions.some((a) => a.kind === "assign" && a.number === pr.number)) continue; // one ask each
    if (!logins(pr.assignees).some(isEric)) {
      actions.push({ kind: "assign", criterion: 4, number: pr.number, title: pr.title, why });
    }
  }
  return { queue, actions, needsYou };
}

/** Criteria 1–3 and the honest queue, for one issue (or a PR GitHub lists as one). */
function planIssue(issue, { markers, now, queue, actions, ask }) {
  const assigned = logins(issue.assignees).some(isEric);
  const marked = markers.has(issue.number);
  const open = (issue.state ?? "open") === "open";
  const act = (kind, criterion, why) =>
    actions.push({ kind, criterion, number: issue.number, title: issue.title, why });

  if (!(open && names(issue.labels).includes(NEEDS_ERIC))) {
    if (marked && assigned) act("unassign", 2, open ? "needs-eric removed" : "issue closed");
    return;
  }
  const decision = decisionLine(issue.body);
  queue.push({
    number: issue.number,
    title: issue.title,
    decision,
    author: issue.user?.login ?? "",
    assigned,
    ageDays: Math.floor((now - Date.parse(issue.created_at ?? now)) / 864e5),
  });
  // No stated decision → a clear candidate, never an ask. Marked → criterion 3, asked once
  // already. Assigned → his by hand; nothing to add.
  const why = `needs-eric with a stated decision: "${decision}"`;
  if (decision && !marked && !assigned) act("assign", 1, why);
  // Needs-you = what he holds after this run: stated, and either his already or about to be. A
  // marked issue he unassigned himself stays off — criterion 3 means the lane won't re-ask.
  if (decision && (assigned || !marked)) {
    ask({ number: issue.number, title: issue.title, criterion: 1, why, decision });
  }
}

/** Criterion 4's test for one PR: held (`hold-merge` or `platter/`), open, ready, ≥12h → hours. */
function heldPrHours(pr, now) {
  if ((pr.state ?? "open") !== "open" || pr.draft) return null;
  const held = names(pr.labels).includes(HOLD_MERGE) || /^platter\//.test(pr.head?.ref ?? "");
  if (!held) return null;
  const hours = (now - Date.parse(pr.created_at ?? now)) / 36e5;
  return hours < HELD_PR_HOURS ? null : hours;
}

/** The dry run's report, as markdown — what Eric reads before anything is switched on. Pure. */
export function report({ queue, actions }) {
  const out = ["## Honest queue — open `needs-eric`", ""];
  if (!queue.length) out.push("_none_");
  else {
    out.push("| # | Waits on | Age | Assigned | Verdict |", "|---|---|---|---|---|");
    for (const q of queue) {
      const verdict = q.decision ? "keep" : "**clear candidate** — no stated decision";
      const waits = q.decision ? q.decision.replaceAll("|", "\\|") : "—";
      out.push(
        `| #${q.number} | ${waits} | ${q.ageDays}d | ${q.assigned ? "yes" : "no"} | ${verdict} |`,
      );
    }
  }
  const clear = queue.filter((q) => !q.decision).length;
  out.push("", `${queue.length} open · ${clear} with no stated decision (listed, not cleared).`);
  out.push("", "## Would do (dry run — nothing written)", "");
  if (!actions.length) out.push("_nothing_");
  for (const a of actions)
    out.push(`- **${a.kind}** #${a.number} (criterion ${a.criterion}) — ${a.why}`);
  return out.join("\n");
}

/** The live REST read both the dry run and the digest plan from — one gather, one `plan()`. */
export function gather() {
  // PRs stay in: a held PR can carry `needs-eric` too (#4361), and GitHub lists it as an issue.
  const issues = ghRestAll(`issues?state=open&labels=${NEEDS_ERIC}`);
  // Criterion 2's candidates: things Eric holds that may have lost the label or closed since.
  const seen = new Set(issues.map((i) => i.number));
  const since = new Date(Date.now() - 14 * 864e5).toISOString();
  for (const i of ghRestAll(`issues?state=all&assignee=${ERIC}&since=${since}`)) {
    if (!seen.has(i.number)) issues.push(i);
  }
  const prs = ghRestAll("pulls?state=open");
  const markers = new Set();
  for (const i of issues) {
    const comments = ghRestAll(`issues/${i.number}/comments`);
    if (comments.some((c) => (c.body ?? "").includes(ASSIGN_MARKER))) markers.add(i.number);
  }
  return { issues, prs, markers };
}

function main(argv) {
  if (!argv.includes("--dry-run")) {
    console.error(
      "assignments: only --dry-run exists. Live assignment is a separate, explicit step after Eric " +
        "has read a dry run (#4289).",
    );
    process.exit(2);
  }
  const planned = plan(gather());
  console.log(argv.includes("--json") ? JSON.stringify(planned, null, 2) : report(planned));
}

if (import.meta.url === `file://${process.argv[1]}`) main(process.argv.slice(2));
