/**
 * The playbook layer — the "third thing" (docs/IDEAS.md): distinct from a persona (a character
 * with a temperament) and a strategy (a decision rule), a playbook is a NAMED condition→action
 * unit with a window, evidence, and per-mode sizing, whose effectiveness is measurable alone.
 *
 * The core abstraction is deliberately tiny: a playbook answers one question per cycle —
 * "what should my book look like right now?" (`desiredState`) — and the engine turns the gap
 * between desired and actual into intents. Entries carry full attribution (playbookId + mode,
 * the seam from plan slice 1); exits are generated by the same engine, which is where S2's
 * exit side lives: a playbook whose window has closed converges to flat, so a held position
 * is flattened BEFORE its print without any separate sweep.
 *
 * Date policy (docs/plans/trade-playbooks.md → decision log): `desiredState` may only open a
 * window on a `confirmed` print date. An estimate never keys an entry — but an already-open
 * position still exits normally when the window closes (safety is never date-gated).
 *
 * EVENT-DRIVEN PLAYS ("TACO Trades"): a calendar answers "how many days to the
 * print"; some plays instead need "did a qualifying external event just fire" — a news hit, not
 * a date. Rather than give TACO its own parallel runner (a second copy of the ownership rule,
 * the sizing math, the flatten-on-close discipline), `desiredState` gained one OPTIONAL third
 * argument: a generic external-event feed. It's optional and additive — S1-NVDA and G1-GOOG
 * ignore it entirely (their `desiredState` keeps its original two-argument shape; JS/TS callers
 * may always pass more arguments than an implementation declares), so their behavior is
 * byte-for-byte unchanged. `PlaybookEvent` is deliberately minimal (symbol + a detection
 * timestamp) so playbook.ts never has to import a specific signal source's module — an
 * event-driven play's own file narrows/consumes it however that source's richer type needs to.
 *
 * PLAYBOOK ANATOMY (#3194, step 2 — additive-only): three optional fields staged for the
 * graduated exit-safety and isolation work. None of them are read by any runtime path yet —
 * `desiredState`/`playbookIntents` above are unchanged — so a playbook that omits all three
 * behaves byte-for-byte as it does today. `horizon` names how long a play's edge is expected to
 * hold (short-horizon plays should tolerate less drawdown before exiting; long-horizon plays
 * tolerate more) and `exitSafety` is the one common dial shape every playbook will eventually
 * fill in rather than inventing its own — both stay inert until the step-4 opt-in wiring reads
 * them. `derivesFrom` is the sole declared exception to decision isolation (a playbook whose
 * logic is explicitly built on another's) — also unread until an isolation audit exists to
 * check it (step 3).
 */
import { daysUntil, type EarningsPrint, nextPrint } from "../domain/earnings-calendar.js";
import { heldQuantity } from "../domain/portfolio.js";
import type { MarketContext, OrderIntent, PlaybookMode, Portfolio } from "../domain/types.js";

/** What a playbook wants its book to look like at a moment in time. */
type DesiredState = "long" | "flat" | "no-window";

/**
 * How long a playbook's edge is expected to hold. Drives the graduated exit-safety dial
 * (#3194): short-horizon plays trip their exit stage on a tighter bar, long-horizon plays on a
 * looser one — same mechanism, different thresholds, never a bespoke exit path per playbook.
 * Unread by any runtime path as of #3194 step 2.
 */
export type PlaybookHorizon = "short" | "medium" | "long";

/**
 * The one exit-safety schema every playbook fills in, rather than inventing its own shape
 * (#3194). `drawdownTripPct` is the peak-to-trough drawdown, as a fraction of the play's own
 * equity contribution, that trips the exit stage; `mode` lets the play's own account owner
 * downgrade enforcement to a notification without disabling the detector. Unread by any runtime
 * path as of #3194 step 2 — wiring lands in step 4, opt-in per playbook.
 */
export interface ExitSafetyDial {
  readonly drawdownTripPct: number;
  readonly mode: "enforce" | "alert-only";
}

/**
 * The event-driven counterpart to a calendar entry: some external source (today, a news hit;
 * a maintained watchlist decides which symbols are even worth listening for — see
 * `src/news/taco-signal.ts`) observed something worth reacting to, at a point in time. Kept
 * minimal on purpose — a richer signal type (e.g. `TacoSignal`, which also carries strength and
 * a headline for attribution) is always assignable here, since it's a structural superset.
 */
export interface PlaybookEvent {
  readonly symbol: string;
  /** ISO-8601 — the event's own timestamp, the clock any entry/hold window runs against. */
  readonly detectedAt: string;
}

export interface Playbook {
  /** e.g. "S1-NVDA" — the id that flows through the attribution seam into every record. */
  readonly id: string;
  /** One symbol per playbook — effectiveness must be measurable alone. */
  readonly symbol: string;
  readonly thesis: string;
  /** Citation into docs/research/ — the record of why this play exists. */
  readonly evidence: string;
  /** Target exposure as a fraction of equity, per mode. Risk guards still clamp on top. */
  readonly size: Readonly<Record<PlaybookMode, number>>;
  /**
   * The condition: given now, the calendar, and (for an event-driven play) recent external
   * events, what should the book be? `events` is optional so date-keyed plays need not declare
   * it at all — see the module doc above.
   */
  desiredState(
    asOfIso: string,
    calendar: readonly EarningsPrint[],
    events?: readonly PlaybookEvent[],
  ): DesiredState;
  /** Optional — see the Playbook Anatomy module doc above. Absent means "no horizon declared,"
   *  which behaves identically to today (no exit-safety wiring reads this yet). */
  readonly horizon?: PlaybookHorizon;
  /** Optional — see the Playbook Anatomy module doc above. Absent means no exit-safety dial is
   *  configured; a playbook with no dial cannot opt into step 4's auto-exit wiring. */
  readonly exitSafety?: ExitSafetyDial;
  /** Optional — the sole declared exception to decision isolation (#3194): the id of the
   *  playbook this one is an explicit derivative of. Absent means fully isolated (the default
   *  for every playbook today). Unverified by any audit until step 3. */
  readonly derivesFrom?: string;
}

/** A playbook enabled in a specific mode — the unit the runner iterates. */
export interface EnabledPlaybook {
  readonly playbook: Playbook;
  readonly mode: PlaybookMode;
}

/** Shared helper for date-keyed windows: days to the symbol's next print, entry-eligible only if confirmed. */
export function printWindow(
  symbol: string,
  asOfIso: string,
  calendar: readonly EarningsPrint[],
): { days: number; confirmed: boolean } | undefined {
  const print = nextPrint(symbol, asOfIso, calendar);
  if (!print) {
    return undefined;
  }
  return { days: daysUntil(asOfIso, print.date), confirmed: print.status === "confirmed" };
}

/**
 * Turn desired-vs-actual into intents for one cycle. Pure — the runner supplies live context.
 *
 * First-cut ownership rule (documented, deliberate): a symbol managed by an enabled playbook is
 * managed ONLY by that playbook — the decorator (`withPlaybooks`) suppresses the base persona's
 * intents on playbook symbols so two decision-makers never fight over one position.
 */
export function playbookIntents(
  enabled: readonly EnabledPlaybook[],
  context: MarketContext,
  portfolio: Portfolio,
  calendar: readonly EarningsPrint[],
  events: readonly PlaybookEvent[] = [],
): OrderIntent[] {
  const intents: OrderIntent[] = [];
  for (const { playbook, mode } of enabled) {
    const state = playbook.desiredState(context.asOf, calendar, events);
    const held = heldQuantity(portfolio, playbook.symbol);
    const quote = context.quotes[playbook.symbol];

    if (state === "long" && held === 0 && quote && quote.ask > 0) {
      const equity = portfolio.cash + held * quote.ask; // playbook symbols enter from flat
      const quantity = Math.floor((playbook.size[mode] * equity) / quote.ask);
      if (quantity > 0) {
        intents.push({
          symbol: playbook.symbol,
          side: "buy",
          quantity,
          type: "market",
          reason: `${playbook.id} window open (${mode}): ${playbook.thesis}`,
          playbookId: playbook.id,
          playbookMode: mode,
        });
      }
    } else if (state === "flat" && held > 0) {
      intents.push({
        symbol: playbook.symbol,
        side: "sell",
        quantity: held,
        type: "market",
        reason: `${playbook.id} window closed (${mode}): exiting per the play's own rule`,
        playbookId: playbook.id,
        playbookMode: mode,
      });
    }
  }
  return intents;
}
