/**
 * The playbook layer — the "third thing" (docs/IDEAS.md): distinct from a persona (a character
 * with a temperament) and a strategy (a decision rule), a playbook is a NAMED condition→action
 * unit with a window, evidence, and per-mode sizing, whose effectiveness is measurable alone.
 *
 * The core abstraction is deliberately tiny: a playbook answers one question per cycle —
 * "what should my book look like right now?" (`desiredState`) — and the engine turns the gap
 * between desired and actual into intents. Entries carry full attribution (playbookId + mode,
 * the seam from plan slice 1); exits are generated by the same engine, which is where S2's
 * exit side lives: a playbook whose window has closed converges to flat, so a held position
 * is flattened BEFORE its print without any separate sweep.
 *
 * Date policy (docs/plans/trade-playbooks.md → decision log): `desiredState` may only open a
 * window on a `confirmed` print date. An estimate never keys an entry — but an already-open
 * position still exits normally when the window closes (safety is never date-gated).
 */
import { daysUntil, type EarningsPrint, nextPrint } from "../domain/earnings-calendar.js";
import { heldQuantity } from "../domain/portfolio.js";
import type { MarketContext, OrderIntent, PlaybookMode, Portfolio } from "../domain/types.js";

/** What a playbook wants its book to look like at a moment in time. */
type DesiredState = "long" | "flat" | "no-window";

export interface Playbook {
  /** e.g. "S1-NVDA" — the id that flows through the attribution seam into every record. */
  readonly id: string;
  /** One symbol per playbook — effectiveness must be measurable alone. */
  readonly symbol: string;
  readonly thesis: string;
  /** Citation into docs/research/ — the record of why this play exists. */
  readonly evidence: string;
  /** Target exposure as a fraction of equity, per mode. Risk guards still clamp on top. */
  readonly size: Readonly<Record<PlaybookMode, number>>;
  /** The condition: given now + the calendar, what should the book be? */
  desiredState(asOfIso: string, calendar: readonly EarningsPrint[]): DesiredState;
}

/** A playbook enabled in a specific mode — the unit the runner iterates. */
export interface EnabledPlaybook {
  readonly playbook: Playbook;
  readonly mode: PlaybookMode;
}

/** Shared helper for date-keyed windows: days to the symbol's next print, entry-eligible only if confirmed. */
export function printWindow(
  symbol: string,
  asOfIso: string,
  calendar: readonly EarningsPrint[],
): { days: number; confirmed: boolean } | undefined {
  const print = nextPrint(symbol, asOfIso, calendar);
  if (!print) {
    return undefined;
  }
  return { days: daysUntil(asOfIso, print.date), confirmed: print.status === "confirmed" };
}

/**
 * Turn desired-vs-actual into intents for one cycle. Pure — the runner supplies live context.
 *
 * First-cut ownership rule (documented, deliberate): a symbol managed by an enabled playbook is
 * managed ONLY by that playbook — the decorator (`withPlaybooks`) suppresses the base persona's
 * intents on playbook symbols so two decision-makers never fight over one position.
 */
export function playbookIntents(
  enabled: readonly EnabledPlaybook[],
  context: MarketContext,
  portfolio: Portfolio,
  calendar: readonly EarningsPrint[],
): OrderIntent[] {
  const intents: OrderIntent[] = [];
  for (const { playbook, mode } of enabled) {
    const state = playbook.desiredState(context.asOf, calendar);
    const held = heldQuantity(portfolio, playbook.symbol);
    const quote = context.quotes[playbook.symbol];

    if (state === "long" && held === 0 && quote && quote.ask > 0) {
      const equity = portfolio.cash + held * quote.ask; // playbook symbols enter from flat
      const quantity = Math.floor((playbook.size[mode] * equity) / quote.ask);
      if (quantity > 0) {
        intents.push({
          symbol: playbook.symbol,
          side: "buy",
          quantity,
          type: "market",
          reason: `${playbook.id} window open (${mode}): ${playbook.thesis}`,
          playbookId: playbook.id,
          playbookMode: mode,
        });
      }
    } else if (state === "flat" && held > 0) {
      intents.push({
        symbol: playbook.symbol,
        side: "sell",
        quantity: held,
        type: "market",
        reason: `${playbook.id} window closed (${mode}): exiting per the play's own rule`,
        playbookId: playbook.id,
        playbookMode: mode,
      });
    }
  }
  return intents;
}
