/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WireRouteImport } from './routes/wire'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as LearnTradingRouteImport } from './routes/learn_.trading'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as UIdIndexRouteImport } from './routes/u.$id.index'
import { Route as UIdDecisionsRouteImport } from './routes/u.$id.decisions'
import { Route as UIdPlaybooksRouteImport } from './routes/u.$id.playbooks'
import { Route as UIdPulseRouteImport } from './routes/u.$id.pulse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WireRoute = WireRouteImport.update({
  id: '/wire',
  path: '/wire',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTradingRoute = LearnTradingRouteImport.update({
  id: '/learn_/trading',
  path: '/learn/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdIndexRoute = UIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UIdRoute,
} as any)
const UIdDecisionsRoute = UIdDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => UIdRoute,
} as any)
const UIdPlaybooksRoute = UIdPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => UIdRoute,
} as any)
const UIdPulseRoute = UIdPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => UIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/join': typeof JoinRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/playbooks': typeof PlaybooksRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/trade': typeof TradeRoute
  '/wire': typeof WireRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/learn/trading': typeof LearnTradingRoute
  '/u/$id': typeof UIdRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/u/$id/decisions': typeof UIdDecisionsRoute
  '/u/$id/playbooks': typeof UIdPlaybooksRoute
  '/u/$id/pulse': typeof UIdPulseRoute
  '/u/$id/': typeof UIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/join': typeof JoinRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/playbooks': typeof PlaybooksRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/trade': typeof TradeRoute
  '/wire': typeof WireRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/learn/trading': typeof LearnTradingRoute
  '/collections': typeof CollectionsIndexRoute
  '/u/$id/decisions': typeof UIdDecisionsRoute
  '/u/$id/playbooks': typeof UIdPlaybooksRoute
  '/u/$id/pulse': typeof UIdPulseRoute
  '/u/$id': typeof UIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/join': typeof JoinRoute
  '/learn': typeof LearnRoute
  '/onboarding': typeof OnboardingRoute
  '/playbooks': typeof PlaybooksRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/trade': typeof TradeRoute
  '/wire': typeof WireRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/learn_/trading': typeof LearnTradingRoute
  '/u/$id': typeof UIdRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/u/$id/decisions': typeof UIdDecisionsRoute
  '/u/$id/playbooks': typeof UIdPlaybooksRoute
  '/u/$id/pulse': typeof UIdPulseRoute
  '/u/$id/': typeof UIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feedback'
    | '/join'
    | '/learn'
    | '/onboarding'
    | '/playbooks'
    | '/research'
    | '/settings'
    | '/trade'
    | '/wire'
    | '/collections/$id'
    | '/learn/trading'
    | '/u/$id'
    | '/collections/'
    | '/u/$id/decisions'
    | '/u/$id/playbooks'
    | '/u/$id/pulse'
    | '/u/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feedback'
    | '/join'
    | '/learn'
    | '/onboarding'
    | '/playbooks'
    | '/research'
    | '/settings'
    | '/trade'
    | '/wire'
    | '/collections/$id'
    | '/learn/trading'
    | '/collections'
    | '/u/$id/decisions'
    | '/u/$id/playbooks'
    | '/u/$id/pulse'
    | '/u/$id'
  id:
    | '__root__'
    | '/'
    | '/feedback'
    | '/join'
    | '/learn'
    | '/onboarding'
    | '/playbooks'
    | '/research'
    | '/settings'
    | '/trade'
    | '/wire'
    | '/collections/$id'
    | '/learn_/trading'
    | '/u/$id'
    | '/collections/'
    | '/u/$id/decisions'
    | '/u/$id/playbooks'
    | '/u/$id/pulse'
    | '/u/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedbackRoute: typeof FeedbackRoute
  JoinRoute: typeof JoinRoute
  LearnRoute: typeof LearnRoute
  OnboardingRoute: typeof OnboardingRoute
  PlaybooksRoute: typeof PlaybooksRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  TradeRoute: typeof TradeRoute
  WireRoute: typeof WireRoute
  CollectionsIdRoute: typeof CollectionsIdRoute
  LearnTradingRoute: typeof LearnTradingRoute
  UIdRoute: typeof UIdRouteWithChildren
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wire': {
      id: '/wire'
      path: '/wire'
      fullPath: '/wire'
      preLoaderRoute: typeof WireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/trading': {
      id: '/learn_/trading'
      path: '/learn/trading'
      fullPath: '/learn/trading'
      preLoaderRoute: typeof LearnTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id/': {
      id: '/u/$id/'
      path: '/'
      fullPath: '/u/$id/'
      preLoaderRoute: typeof UIdIndexRouteImport
      parentRoute: typeof UIdRoute
    }
    '/u/$id/decisions': {
      id: '/u/$id/decisions'
      path: '/decisions'
      fullPath: '/u/$id/decisions'
      preLoaderRoute: typeof UIdDecisionsRouteImport
      parentRoute: typeof UIdRoute
    }
    '/u/$id/playbooks': {
      id: '/u/$id/playbooks'
      path: '/playbooks'
      fullPath: '/u/$id/playbooks'
      preLoaderRoute: typeof UIdPlaybooksRouteImport
      parentRoute: typeof UIdRoute
    }
    '/u/$id/pulse': {
      id: '/u/$id/pulse'
      path: '/pulse'
      fullPath: '/u/$id/pulse'
      preLoaderRoute: typeof UIdPulseRouteImport
      parentRoute: typeof UIdRoute
    }
  }
}

interface UIdRouteChildren {
  UIdDecisionsRoute: typeof UIdDecisionsRoute
  UIdPlaybooksRoute: typeof UIdPlaybooksRoute
  UIdPulseRoute: typeof UIdPulseRoute
  UIdIndexRoute: typeof UIdIndexRoute
}

const UIdRouteChildren: UIdRouteChildren = {
  UIdDecisionsRoute: UIdDecisionsRoute,
  UIdPlaybooksRoute: UIdPlaybooksRoute,
  UIdPulseRoute: UIdPulseRoute,
  UIdIndexRoute: UIdIndexRoute,
}

const UIdRouteWithChildren = UIdRoute._addFileChildren(UIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedbackRoute: FeedbackRoute,
  JoinRoute: JoinRoute,
  LearnRoute: LearnRoute,
  OnboardingRoute: OnboardingRoute,
  PlaybooksRoute: PlaybooksRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  TradeRoute: TradeRoute,
  WireRoute: WireRoute,
  CollectionsIdRoute: CollectionsIdRoute,
  LearnTradingRoute: LearnTradingRoute,
  UIdRoute: UIdRouteWithChildren,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
