#!/usr/bin/env node
// ISSUES — the one command for the high-volume issue chores: create · update · search · show.
//
// WHY (Eric, 2026-09-29: "creating issues and mapping them to our storyboard will be a high volume
// activity, it needs to be efficient"). Filing one issue by hand was five steps — draft, lint,
// JSON-encode, POST, re-read to verify — and each session re-derived them, often over the GitHub
// MCP (GraphQL, the scarce bucket). This folds them into one REST call path with the gates built in:
//
//   - create lints the capsule (issue-lint.mjs) and REFUSES on a problem, searches open issues for a
//     same-titled duplicate and REFUSES on a hit (--force to override), appends the attribution
//     footer if missing, then prints one line: `#N [Board status] title`.
//   - the board column is never set here. It follows labels: moneypenny-events.yml's sync-project
//     job runs projects-sync.mjs on every label change, and statusForIssue() maps needs-eric/
//     needs-info → Blocked, ready → Ready, closed → Done. So "make it Blocked" is `--add needs-eric`.
//     `show`/`search` print the column that rule yields, so a session can check without GraphQL.
//
//   node scripts/issues.mjs create --title "…" --body-file b.md [--labels a,b] [--force] [--dry-run]
//   node scripts/issues.mjs update 123 [--body-file b.md] [--title "…"] [--add a,b] [--remove c]
//                                      [--close completed|not_planned] [--reopen] [--comment-file c.md]
//   node scripts/issues.mjs search "words" [--label x] [--state open|closed|all] [--limit 20] [--json]
//     (every word must appear in title or body; --label filters; newest first)
//   node scripts/issues.mjs show 123 [--json]
//
// Token: GH_TOKEN or GITHUB_TOKEN (REST core bucket). Repo: GITHUB_REPOSITORY or ejclark/skynet-capital.
import { readFileSync } from "node:fs";
import { lintIssue } from "./issue-lint.mjs";
import { ghRest, ghRestAll, sh } from "./moneypenny/gh.mjs";
import { FOOTER } from "./moneypenny/labels.mjs";
import { statusForIssue } from "./moneypenny/projects.mjs";

const REPO = () => process.env.GITHUB_REPOSITORY ?? "ejclark/skynet-capital";
const TOKEN = () => process.env.GH_TOKEN ?? process.env.GITHUB_TOKEN ?? "";

// ─── pure core (specced in tests/scripts/issues.spec.ts) ─────────────────────────────────────────

const VALUE_FLAGS = new Set([
  "--title",
  "--body-file",
  "--labels",
  "--add",
  "--remove",
  "--close",
  "--comment-file",
  "--label",
  "--state",
  "--limit",
]);

/** argv → { cmd, positional, flags }. Value flags take the next arg; the rest are booleans. */
export function parseArgs(argv) {
  const [cmd, ...rest] = argv;
  const flags = {};
  const positional = [];
  for (let i = 0; i < rest.length; i++) {
    const a = rest[i];
    if (VALUE_FLAGS.has(a)) flags[a.slice(2)] = rest[++i];
    else if (a.startsWith("--")) flags[a.slice(2)] = true;
    else positional.push(a);
  }
  return { cmd, positional, flags };
}

export const csv = (s) =>
  String(s ?? "")
    .split(",")
    .map((x) => x.trim())
    .filter(Boolean);

/** Lowercase word set, punctuation and 1–2 letter words dropped — the unit dedupe compares. */
export function titleWords(title) {
  return new Set(
    String(title)
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, " ")
      .split(/\s+/)
      .filter((w) => w.length > 2),
  );
}

/**
 * Open issues whose title is the same ask: identical word sets, or ≥80% overlap (Jaccard). High on
 * purpose — a false "duplicate" blocks a real filing, and --force exists for the near-misses.
 */
export function findDuplicates(title, issues, threshold = 0.8) {
  const mine = titleWords(title);
  if (mine.size === 0) return [];
  return issues.filter((issue) => {
    const theirs = titleWords(issue.title);
    const shared = [...mine].filter((w) => theirs.has(w)).length;
    const union = new Set([...mine, ...theirs]).size;
    return union > 0 && shared / union >= threshold;
  });
}

export const withFooter = (body) =>
  body.includes("Generated by [Claude Code]") ? body : `${body.trimEnd()}\n\n${FOOTER}\n`;

const labelNames = (issue) => (issue.labels ?? []).map((l) => (typeof l === "string" ? l : l.name));

/** The board column statusForIssue() yields — what projects-sync.mjs will set on its next run. */
export const boardStatus = (issue) =>
  statusForIssue({ state: issue.state, labels: labelNames(issue) });

/** One scan-able line per issue: `#N [Status] title (labels)`. */
export function row(issue) {
  const labels = labelNames(issue);
  const tail = labels.length ? `  (${labels.join(", ")})` : "";
  return `#${issue.number} [${boardStatus(issue)}] ${issue.title}${tail}`;
}

/** Label set after an edit — current ∪ add ∖ remove, order kept, no duplicates. */
export function nextLabels(current, add = [], remove = []) {
  const drop = new Set(remove);
  return [...new Set([...current, ...add])].filter((l) => !drop.has(l));
}

/**
 * Does this issue match a `search`? Every word must appear in the title or body (case-insensitive),
 * and the label, when given, must be on it. Local on purpose: cloud sessions are refused GitHub's
 * global /search endpoint ("sessions are bound to their configured repositories"), so matching
 * runs over the repo-scoped issue list instead — the same answer in a session and in CI.
 */
export function matches(issue, words, { label } = {}) {
  if (label && !labelNames(issue).includes(label)) return false;
  const hay = `${issue.title}\n${issue.body ?? ""}`.toLowerCase();
  return String(words ?? "")
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean)
    .every((w) => hay.includes(w));
}

// ─── IO (REST core bucket, curl so HTTPS_PROXY is honoured — see gh.mjs's ghRest header) ──────────

function ghWrite(method, path, payload) {
  const out = sh(
    "curl",
    [
      "-sS",
      "--fail-with-body",
      "-X",
      method,
      "-H",
      `Authorization: Bearer ${TOKEN()}`,
      "-H",
      "Accept: application/vnd.github+json",
      "-H",
      "User-Agent: skynet-issues",
      // Without it curl sends `--data-binary` as form-urlencoded and the API answers 415 — the
      // first real filing through this command hit exactly that (2026-09-29).
      "-H",
      "Content-Type: application/json",
      "--data-binary",
      "@-",
      `https://api.github.com/repos/${REPO()}/${path}`,
    ],
    { input: JSON.stringify(payload) },
  );
  return JSON.parse(out || "null");
}

/** Every issue in `state` (PRs dropped — the issues endpoint returns both), newest first. */
function listIssues(state = "open") {
  return ghRestAll(`issues?state=${state}&sort=created&direction=desc`).filter(
    (i) => !i.pull_request,
  );
}

const readBody = (file) => readFileSync(file, "utf8");

function lintOrDie({ title, body, labels }) {
  const { problems, notes } = lintIssue({ title, body, labels });
  for (const n of notes) console.error(`note: ${n}`);
  if (problems.length) {
    for (const p of problems) console.error(`problem: ${p}`);
    console.error("issues: refused — fix the capsule (docs/ISSUES.md), then re-run.");
    process.exit(1);
  }
}

function create({ flags }) {
  const title = flags.title;
  if (!(title && flags["body-file"])) throw new Error("create needs --title and --body-file");
  const labels = csv(flags.labels);
  const body = withFooter(readBody(flags["body-file"]));
  lintOrDie({ title, body, labels });

  if (!flags.force) {
    const dupes = findDuplicates(title, listIssues("open"));
    if (dupes.length) {
      for (const d of dupes) console.error(`duplicate? ${row(d)}  ${d.html_url}`);
      console.error("issues: refused — update the existing issue, or re-run with --force.");
      process.exit(1);
    }
  }
  if (flags["dry-run"]) return console.log(`dry-run ok: would file "${title}" [${labels}]`);
  const issue = ghWrite("POST", "issues", { title, body, labels });
  console.log(`${row(issue)}  ${issue.html_url}`);
}

function update({ positional, flags }) {
  const n = Number(positional[0]);
  if (!n) throw new Error("update needs an issue number");
  const current = ghRest(`issues/${n}`);
  const patch = {};
  if (flags.title) patch.title = flags.title;
  if (flags["body-file"]) {
    patch.body = withFooter(readBody(flags["body-file"]));
    lintOrDie({
      title: flags.title ?? current.title,
      body: patch.body,
      labels: labelNames(current),
    });
  }
  if (flags.add || flags.remove) {
    patch.labels = nextLabels(labelNames(current), csv(flags.add), csv(flags.remove));
  }
  if (flags.close) Object.assign(patch, { state: "closed", state_reason: flags.close });
  if (flags.reopen) patch.state = "open";
  const issue = Object.keys(patch).length ? ghWrite("PATCH", `issues/${n}`, patch) : current;
  if (flags["comment-file"]) {
    ghWrite("POST", `issues/${n}/comments`, { body: withFooter(readBody(flags["comment-file"])) });
  }
  console.log(`${row(issue)}  ${issue.html_url}`);
}

function search({ positional, flags }) {
  const words = positional.join(" ");
  const items = listIssues(flags.state ?? "open")
    .filter((i) => matches(i, words, { label: flags.label }))
    .slice(0, Number(flags.limit ?? 20));
  if (flags.json)
    return console.log(JSON.stringify(items.map((i) => ({ ...i, board: boardStatus(i) }))));
  for (const i of items) console.log(row(i));
  if (!items.length) console.log("(no matches)");
}

function show({ positional, flags }) {
  const issue = ghRest(`issues/${Number(positional[0])}`);
  if (flags.json) return console.log(JSON.stringify({ ...issue, board: boardStatus(issue) }));
  console.log(`${row(issue)}  ${issue.html_url}`);
}

const COMMANDS = { create, update, search, show };

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = parseArgs(process.argv.slice(2));
  const run = COMMANDS[args.cmd];
  if (!run) {
    console.error("usage: node scripts/issues.mjs <create|update|search|show> … (see file header)");
    process.exit(2);
  }
  try {
    run(args);
  } catch (err) {
    console.error(`issues: ${err.stderr || err.message}`);
    process.exit(1);
  }
}
