// THE VOCABULARY POSTMASTER.MJS SPEAKS — split out of postmaster.mjs (2026-08-26, the
// noExcessiveLinesPerFile split) so the label/comment vocabulary has one home shared by every lane
// (the router itself, the event lane, the shipped-issue closer, the stall auditor) — and, since a
// label is only real once GitHub has it, the code that provisions it too.
import { sh } from "./postmaster-gh.mjs";

// ── labels this repo speaks ───────────────────────────────────────────────────
export const LABELS = {
  event: {
    name: "event-research",
    color: "0e8a16",
    description: "A calendar event awaiting initial research",
  },
  stall: {
    name: "stall-flagged",
    color: "d93f0b",
    description: "The stall audit pinged this once — dispatched work nothing has claimed",
  },
  // The feedback lane's terminal-state vocabulary. These were applied only by a build session's
  // prompt compliance, with nothing guaranteeing they existed — `gh issue edit --add-label` on a
  // missing label fails, which would silently void the lane's "never end in silence" rule.
  //
  // Three of the four outcomes below cost Eric NOTHING. That split is the point: before it,
  // `needs-eric` was the only non-PR exit, so "too big", "unclear what the member wants" and
  // "genuinely his call" all landed in one queue and buried the third in the first two.
  curated: {
    name: "curated",
    color: "0e8a16",
    description: "Written through the AI coach — its build spec is the spec; build it unattended",
  },
  needsInfo: {
    name: "needs-info",
    color: "fbca04",
    description: "Waiting on the MEMBER to clarify — never on Eric",
  },
  nextSlice: {
    name: "next-slice",
    color: "1d76db",
    description: "First slice shipped; the remainder is captured on the issue",
  },
  needsEric: {
    name: "needs-eric",
    color: "d93f0b",
    description: "A decision only Eric can make — the irreversible class or a genuine taste fork",
  },
  plan: {
    name: "plan",
    color: "5319e7",
    description: "A plan issue awaiting Eric's ready-flip — not blocked on a decision",
  },
};

/** Appended to every issue/comment body a lane posts, so provenance is never ambiguous. */
export const FOOTER = "---\n_Generated by [Claude Code](https://claude.ai/code)_";

/**
 * Upsert every label this repo's prompts name. Until 2026-08-22 only `event-research` and
 * `stall-flagged` were ever passed to `ensureLabel`, so `curated`, `needs-info` and `next-slice`
 * were declared in LABELS and **never created** — they 404'd on the repo. A build session told to
 * end in `needs-info` therefore hit a failing `gh issue edit --add-label` and fell back to the two
 * exits that did exist: a PR, or `needs-eric`. The four-state design was two-thirds fictional.
 *
 * Cheap and idempotent, so it runs on every postmaster invocation rather than per-intent.
 */
export function ensureVocabulary() {
  for (const label of Object.values(LABELS)) ensureLabel(label);
}

export function ensureLabel(label) {
  // GitHub auto-creates a label the first time it is applied, but as default grey with no
  // description. Upsert so the repo self-provisions and nobody has to know it needed doing.
  const body = JSON.stringify(label);
  const base = `https://api.github.com/repos/${process.env.GITHUB_REPOSITORY}/labels`;
  const auth = [
    "-H",
    `Authorization: Bearer ${process.env.GH_TOKEN ?? ""}`,
    "-H",
    "Accept: application/vnd.github+json",
  ];
  try {
    // --fail is load-bearing: without it curl exits 0 on a 404 body (the label doesn't exist
    // yet), the PATCH "succeeds," and the POST-create fallback below never runs — the label is
    // silently never created (docs/LESSONS.md 2026-08-19, the missing `stall-flagged` label).
    sh("curl", ["-sS", "--fail", "-X", "PATCH", ...auth, `${base}/${label.name}`, "-d", body]);
  } catch {
    try {
      sh("curl", ["-sS", "--fail", "-X", "POST", ...auth, base, "-d", body]);
    } catch {
      /* a label that already exists is a harmless 422 */
    }
  }
}
