#!/usr/bin/env node
// THE POSTMASTER — one router for every issue-driven automation in this repo.
//
//   node scripts/postmaster.mjs                          # read $GITHUB_EVENT_PATH, act
//   node scripts/postmaster.mjs --dry-run --event f.json # print the intents, touch nothing
//
// WHY THIS EXISTS (Eric, 2026-08-17: "the handoff system has a lot of workflows which feels
// extra… it'd be nice to have a postmaster"). Four workflows had grown to 482 lines carrying **202
// lines of bash inside `run:` blocks** — the one corner of this repo that escaped its own
// pure-functions-with-specs doctrine, and precisely where the defects lived. The 2026-08-17
// double-fire (two runs, two receipts, and with a real zip two imports racing the same branch) was
// a trigger-and-bash bug no spec could have caught, because there was no spec.
//
// THE SHAPE: **decide, then do.** `route()` is pure — an event plus its dependencies in, a list of
// intents out. `execute()` is the only part that touches GitHub or git. Every routing branch is
// therefore testable by feeding a fixture payload (tests/fixtures/events/), which is the whole
// point of the exercise.
//
// GitHub hands the entire event payload to a workflow at $GITHUB_EVENT_PATH, so the router needs no
// bespoke plumbing to know what happened — it reads one JSON file.
//
// WHAT IT DOES NOT OWN: the scanners (`handoff-scan.mjs`, `event-scan.mjs`) and the importer
// (`handoff-import.mjs`) stay exactly as they are and are invoked, never reimplemented — they carry
// their own hard-won failure modes (docs/LESSONS.md 2026-08-14).
import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";

// ── labels this repo speaks ───────────────────────────────────────────────────
export const LABELS = {
  handoff: {
    name: "handoff",
    color: "5319e7",
    description: "A Claude Design bundle waiting to be built",
  },
  event: {
    name: "event-research",
    color: "0e8a16",
    description: "A calendar event awaiting initial research",
  },
  inbox: {
    name: "handoff-inbox",
    color: "1d76db",
    description: "Drop a design zip here — the inbox imports it and opens the handoff PR",
  },
  stall: {
    name: "stall-flagged",
    color: "d93f0b",
    description: "The stall audit pinged this once — dispatched work nothing has claimed",
  },
};

const FOOTER = "---\n_Generated by [Claude Code](https://claude.ai/code)_";

/** Kebab-case slug, identical to handoff-import.mjs so a flip targets what was imported. */
export const slugify = (s) =>
  String(s ?? "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

// ── the pure half ─────────────────────────────────────────────────────────────

/**
 * Decide what should happen. Pure: no network, no disk, no clock.
 *
 * @param ctx  { eventName, action, payload, inputs, repo, actor }
 * @param deps { readyHandoffs[], dueEvents[], openIssueTitles[], openPrHeads[], handoffStatus(slug) }
 * @returns Intent[]  — `[]` means "nothing to do", which is the common and correct outcome.
 */
export function route(ctx, deps = {}) {
  if (ctx.eventName === "push" || ctx.inputs?.command === "scan") return routeSweep(deps);
  if (ctx.eventName === "issues") return routeInboxLabel(ctx, deps);
  if (ctx.eventName === "workflow_dispatch" && ctx.inputs?.command === "flip-handoff") {
    return routeFlip(ctx, deps);
  }
  if (ctx.eventName === "workflow_dispatch" && ctx.inputs?.command === "release-claim") {
    return routeRelease(ctx);
  }
  return [];
}

/** A handoff or event landed on main (or the `scan` command re-ran the sweep by hand — same path,
 *  never a second one that can drift). One issue per ready handoff / never-assessed event, deduped
 *  by exact open-issue title. */
function routeSweep(deps) {
  const { readyHandoffs = [], dueEvents = [], openIssueTitles = [] } = deps;
  const intents = [];
  const queued = new Set(openIssueTitles);
  for (const h of readyHandoffs) {
    const title = `[handoff] ${h.slug}`;
    if (queued.has(title)) continue;
    queued.add(title);
    intents.push({ kind: "open-issue", label: LABELS.handoff, title, body: handoffIssueBody(h) });
  }
  for (const e of dueEvents.filter((x) => x.reason === "never-assessed")) {
    const title = `[event-research] ${e.id}`;
    if (queued.has(title)) continue;
    queued.add(title);
    intents.push({ kind: "open-issue", label: LABELS.event, title, body: eventIssueBody(e) });
  }
  return intents;
}

/** A zip was dropped on an issue. Gate on the label JUST applied — reading the issue's whole label
 *  set is what made the old workflow fire twice (`opened` + `labeled` both matched). */
function routeInboxLabel(ctx, deps) {
  const { openPrHeads = [] } = deps;
  if (ctx.action !== "labeled" || ctx.payload?.label?.name !== LABELS.inbox.name) {
    return [{ kind: "noop", reason: "not a handoff-inbox labelling" }];
  }
  const issue = ctx.payload.issue ?? {};
  const slug = slugify(issue.title) || `handoff-${issue.number}`;

  // Re-applying the label is a legitimate retry, but it must not import twice.
  if (openPrHeads.includes(`handoff/${slug}`)) {
    return [
      {
        kind: "comment",
        issueNumber: issue.number,
        body: `Already imported — a PR for \`handoff/${slug}\` is open. Close or merge it before re-importing.\n\n${FOOTER}`,
      },
    ];
  }

  const url = findZipUrl(issue.body ?? "");
  if (!url) {
    return [
      {
        kind: "comment",
        issueNumber: issue.number,
        body: `No \`.zip\` attachment found in this issue's body, so there was nothing to import.\n\nDrag the design bundle into the issue description (not a comment) and re-apply the \`${LABELS.inbox.name}\` label. Attachments cap at 25 MB.\n\n${FOOTER}`,
      },
    ];
  }
  return [{ kind: "import-zip", url, slug, issueNumber: issue.number }];
}

/** The flip button — refuse anything that is not a real, currently-draft handoff. */
function routeFlip(ctx, deps) {
  const { handoffStatus = () => null } = deps;
  const slug = slugify(ctx.inputs.slug);
  if (!slug) return [{ kind: "error", reason: "no slug given" }];
  const status = handoffStatus(slug);
  if (status === null) return [{ kind: "error", reason: `no handoff at docs/handoffs/${slug}` }];
  if (status !== "draft") {
    return [
      { kind: "error", reason: `${slug} is '${status}', not 'draft' — nothing to authorize` },
    ];
  }
  return [{ kind: "flip-handoff", slug, actor: ctx.actor }];
}

/**
 * Break a wedged lease by hand.
 *
 * The claim is a *lease*, not a lock, so it self-heals in two hours — but two hours is a long time
 * to stare at a handoff that is provably dead, and the only other way to clear one is deleting a
 * ref through the API, which needs a token nobody carrying a phone has. That made "the build died
 * holding the claim" a step on Eric's list, which is the one place a step must never be
 * (CLAUDE.md: action-required-from-Eric ≈ zero). So it becomes a button.
 *
 * Deliberately a **dispatch only** — never something the sweep does on its own. Auto-releasing
 * another run's claim would defeat the lease it is built on; deciding a build is dead is judgment,
 * and judgment stays with the human who dispatched.
 */
function routeRelease(ctx) {
  const slug = slugify(ctx.inputs?.slug);
  if (!slug) return [{ kind: "error", reason: "no slug given" }];
  return [{ kind: "release-claim", slug, actor: ctx.actor }];
}

/**
 * THE LOOP'S EYES (harness-research gap #3: "the loop has a mouth but no eyes"). The router
 * dispatches work; nothing watched whether dispatched work ever moved. `audit()` is the pure half
 * of a stall supervisor: given every `executing` handoff's quiet time and every open dispatch
 * issue that nothing has claimed, emit flag-stall intents past a threshold.
 *
 * Deliberately DETERMINISTIC and ceiling-capped: it comments and warns — it never reclaims a lock,
 * reassigns work, or flips a status. Deciding whether a stalled build is dead or just slow is
 * judgment, and judgment belongs to the humans and agents the comment summons.
 */
export function audit(deps = {}) {
  const { executingHandoffs = [], unclaimedIssues = [], staleAfterDays = 2 } = deps;
  // FLAG ONCE, NOT PER RUN. The audit rides every push (2026-08-19), so without memory a stall
  // would draw a fresh comment on every merge to main — comment spam, not eyes. The memory is the
  // `stall-flagged` label: executeOne applies it with the comment, and a labelled issue is never
  // re-flagged. One ping per stall, however many pushes go by.
  const flagged = new Set(deps.alreadyFlagged ?? []);
  const intents = [];
  for (const h of executingHandoffs) {
    if (h.quietDays < staleAfterDays) continue;
    if (h.issueNumber && flagged.has(h.issueNumber)) continue;
    intents.push({
      kind: "flag-stall",
      slug: h.slug,
      issueNumber: h.issueNumber,
      quietDays: h.quietDays,
      body: `⏱ **Stall check** — \`${h.slug}\` flipped to \`executing\` (the lock) but its handoff folder has seen no commit in **${h.quietDays} day(s)**.\n\nIf the build is dead, a human should flip the status back to \`ready\` so a pickup layer can re-claim it — the lock is only honest while its holder is alive.\n\n${FOOTER}`,
    });
  }
  for (const i of unclaimedIssues) {
    if (i.quietDays < staleAfterDays) continue;
    if (flagged.has(i.number)) continue;
    intents.push({
      kind: "flag-stall",
      issueNumber: i.number,
      title: i.title,
      quietDays: i.quietDays,
      body: `⏱ **Stall check** — this was dispatched **${i.quietDays} day(s)** ago and no pickup layer has claimed it (no \`executing\` flip, no ledger). The push-driven sweep may be failing, or every layer saw a non-ready status.\n\n${FOOTER}`,
    });
  }
  return intents;
}

/**
 * Which due events actually get researched this run. Pure, and the reason the event lane can ride
 * EVERY push without double-working: the research session's branch name is mandated as
 * `research/<event-id>`, so an event whose research PR is still open (merged PRs leave the list)
 * is filtered out here. Concurrency serializes postmaster runs, so each run sees the last one's
 * open PRs — the pair is the dedupe.
 */
export function dueForResearch(dueEvents = [], openPrHeads = []) {
  const inFlight = new Set(openPrHeads);
  return dueEvents.filter((e) => !inFlight.has(`research/${e.id}`));
}

/**
 * The attachment URL, out of an issue body. Non-image attachments render as plain links under
 * `/user-attachments/files/<id>/<name>`; images use `/assets/`, and matching only that form is the
 * trap that has bitten other integrations.
 */
export function findZipUrl(body) {
  const m = String(body).match(
    /https:\/\/github\.com\/user-attachments\/files\/\d+\/[^\s)"'>]+\.zip/,
  );
  return m ? m[0] : null;
}

function handoffIssueBody(h) {
  const files = (h.files ?? []).map((f) => `- \`${f}\``).join("\n");
  return [
    `@claude — a design handoff is ready to build: **${h.title}**`,
    "",
    `Its contract is [\`${h.readme}\`](../blob/main/${h.readme}). Read it first, then follow the`,
    "execution discipline in [`docs/HANDOFFS.md`](../blob/main/docs/HANDOFFS.md) — in short:",
    "",
    "1. Flip the handoff's status `ready` → `executing` in your first commit (that is the lock).",
    "2. Reconcile the bundle's tokens against `docs/BRAND.md` before writing code — **the brand wins** on conflict, and the divergence gets a decision-log line.",
    "3. Reuse `src/ui` before adding anything; ship small green PRs via `/ship`.",
    "4. Verify every EARS criterion by its named verification, then flip the status to `review` and close this issue with the PR link.",
    "",
    `Bundle at \`${h.path}\`:`,
    "",
    files,
    "",
    FOOTER,
  ].join("\n");
}

function eventIssueBody(e) {
  return [
    `@claude — a calendar event is awaiting initial research: **${e.title}** (${e.date}, ${e.status}, impact: ${e.impact})`,
    "",
    "Run the `never-assessed` mode of [`docs/process/EVENT-RESEARCH.md`](../blob/main/docs/process/EVENT-RESEARCH.md):",
    `produce \`${e.ledger}\` from its TEMPLATE (initial research + stance + kill switches + first`,
    "ledger row), and ship it via `/ship`. The postmaster's push-driven sweep takes the pulse",
    "checks from there.",
    "",
    FOOTER,
  ].join("\n");
}

// ── the claim lease ───────────────────────────────────────────────────────────

/**
 * ATOMIC CLAIM (Eric, 2026-08-17: "waiting for commits to a doc file — seems flimsy af"). He was
 * right, and the canary proved it: a session ran 11 minutes, spent 43k tokens, and left the repo
 * with no trace at all, because the only claim signal was a commit that had not happened yet.
 *
 * The lease fixes that with git's own atomicity: `POST /git/refs` **fails with 422 if the ref
 * already exists**, so creating `claim/<slug>` is a genuine compare-and-set — first writer wins, no
 * read-then-write race, no prose parsing. And it happens BEFORE any work, so a claim is visible in
 * seconds rather than at first commit.
 *
 * It is a LEASE, not a lock: a claim older than `staleAfterMs` is reclaimable, because a session
 * that died holding a permanent lock would wedge the handoff forever — which is the failure mode
 * this whole exercise exists to remove.
 */
export const CLAIM_TTL_MS = 2 * 60 * 60 * 1000; // 2h — well past any honest build

/** @returns {{ claimed: boolean, reason: string }} */
export function claimHandoff(slug, sha, nowMs, staleAfterMs = CLAIM_TTL_MS) {
  const ref = `claim/${slug}`;
  const existing = (() => {
    try {
      return JSON.parse(sh("gh", ["api", `repos/{owner}/{repo}/git/ref/heads/${ref}`]));
    } catch {
      return null; // 404 — unclaimed, the common case
    }
  })();

  if (existing) {
    const age = nowMs - Date.parse(claimAgeOf(existing.object.sha));
    if (age < staleAfterMs) {
      return { claimed: false, reason: `held by a live claim (${Math.round(age / 60000)}m old)` };
    }
    // Stale: the holder died. Reclaim rather than wedge the handoff forever.
    try {
      sh("gh", ["api", "-X", "DELETE", `repos/{owner}/{repo}/git/refs/heads/${ref}`]);
    } catch {
      /* someone else just cleaned it up — the create below will arbitrate */
    }
  }

  try {
    sh("gh", [
      "api",
      "-X",
      "POST",
      "repos/{owner}/{repo}/git/refs",
      "-f",
      `ref=refs/heads/${ref}`,
      "-f",
      `sha=${sha}`,
    ]);
    return { claimed: true, reason: existing ? "reclaimed a stale lease" : "claimed" };
  } catch {
    // 422 — another runner won the race between our check and our create. That is the lock working.
    return { claimed: false, reason: "lost the race to a concurrent claim" };
  }
}

/** Committer date of the claim's commit, for lease age. */
function claimAgeOf(sha) {
  try {
    return JSON.parse(sh("gh", ["api", `repos/{owner}/{repo}/commits/${sha}`])).commit.committer
      .date;
  } catch {
    return new Date(0).toISOString(); // unreadable → treat as ancient, i.e. reclaimable
  }
}

/** Release a lease once the handoff is no longer being built. */
export function releaseClaim(slug) {
  try {
    sh("gh", ["api", "-X", "DELETE", `repos/{owner}/{repo}/git/refs/heads/claim/${slug}`]);
    return true;
  } catch {
    return false;
  }
}

// ── the impure half ───────────────────────────────────────────────────────────

const sh = (cmd, args, opts = {}) =>
  execFileSync(cmd, args, { encoding: "utf8", stdio: "pipe", ...opts }).trim();

/**
 * Read the real dependencies: scanners, open issues, open PR heads, on-disk statuses.
 *
 * FAIL CLOSED, LOUDLY. An earlier draft swallowed errors and returned `[]` — which made a failed
 * `gh issue list` indistinguishable from "no open issues", so the title-dedupe silently disarmed
 * and the duplicate class this router exists to kill was re-armed by its own plumbing (the
 * harness-engineering research called this the top gap). A dependency that cannot be read is a
 * hard stop, not an empty list.
 */
function gatherDeps(ctx) {
  const json = (label, cmd, args) => {
    let out;
    try {
      out = sh(cmd, args);
    } catch (err) {
      throw new Error(`${label} failed: ${String(err.stderr || err.message).trim()}`);
    }
    try {
      return JSON.parse(out || "[]");
    } catch {
      throw new Error(`${label} returned unparseable JSON:\n${out.slice(0, 400)}`);
    }
  };
  const needsScan = ctx.eventName === "push" || ctx.inputs?.command === "scan";
  return {
    readyHandoffs: needsScan
      ? json("handoff-scan --ready", "node", ["scripts/handoff-scan.mjs", "--ready"])
      : [],
    dueEvents: needsScan
      ? json("event-scan --due", "node", ["scripts/event-scan.mjs", "--due"])
      : [],
    openIssueTitles: needsScan
      ? json("gh issue list", "gh", [
          "issue",
          "list",
          "--state",
          "open",
          "--limit",
          "100",
          "--json",
          "title",
        ]).map((i) => i.title)
      : [],
    openPrHeads: json("gh pr list", "gh", [
      "pr",
      "list",
      "--state",
      "open",
      "--limit",
      "100",
      "--json",
      "headRefName",
    ]).map((p) => p.headRefName),
    handoffStatus: (slug) => {
      const readme = `docs/handoffs/${slug}/README.md`;
      if (!existsSync(readme)) return null;
      const m = readFileSync(readme, "utf8").match(/^\*\*Status:\*\* *([a-z]+)/m);
      return m ? m[1] : null;
    },
  };
}

/** Audit-mode dependencies: quiet-time per executing handoff, unclaimed dispatch issues. Loud on
 *  failure, same doctrine as gatherDeps. `now` injected for the day math (never Date.now() in a
 *  testable path — the caller passes it). */
function gatherAuditDeps(nowMs) {
  const json = (label, args) => {
    let out;
    try {
      out = sh("gh", args);
    } catch (err) {
      throw new Error(`${label} failed: ${String(err.stderr || err.message).trim()}`);
    }
    try {
      return JSON.parse(out || "[]");
    } catch {
      throw new Error(`${label} returned unparseable JSON:\n${out.slice(0, 400)}`);
    }
  };
  const daysSince = (iso) => Math.floor((nowMs - Date.parse(iso)) / 86_400_000);
  const issues = json("gh issue list", [
    "issue",
    "list",
    "--state",
    "open",
    "--limit",
    "100",
    "--json",
    "title,number,updatedAt,labels",
  ]);
  const issueFor = (slug) => issues.find((i) => i.title === `[handoff] ${slug}`);
  const alreadyFlagged = issues
    .filter((i) => (i.labels ?? []).some((l) => l.name === LABELS.stall.name))
    .map((i) => i.number);

  const executingHandoffs = [];
  const unclaimedIssues = [];
  for (const dir of existsSync("docs/handoffs") ? readdirSync("docs/handoffs") : []) {
    const readme = `docs/handoffs/${dir}/README.md`;
    if (!existsSync(readme) || dir === "TEMPLATE.md") continue;
    const status = readFileSync(readme, "utf8").match(/^\*\*Status:\*\* *([a-z]+)/m)?.[1];
    if (status === "executing") {
      const lastCommit = sh("git", ["log", "-1", "--format=%cI", "--", `docs/handoffs/${dir}`]);
      executingHandoffs.push({
        slug: dir,
        quietDays: lastCommit ? daysSince(lastCommit) : 999,
        issueNumber: issueFor(dir)?.number,
      });
    }
    if (status === "ready") {
      const issue = issueFor(dir);
      if (issue)
        unclaimedIssues.push({
          title: issue.title,
          number: issue.number,
          quietDays: daysSince(issue.updatedAt),
        });
    }
  }
  for (const i of issues) {
    const id = i.title.match(/^\[event-research\] (.+)$/)?.[1];
    if (id && !existsSync(`docs/research/events/${id}.md`)) {
      unclaimedIssues.push({ title: i.title, number: i.number, quietDays: daysSince(i.updatedAt) });
    }
  }
  return { executingHandoffs, unclaimedIssues, alreadyFlagged };
}

function execute(intents) {
  const receipt = [];
  for (const i of intents) {
    receipt.push(executeOne(i));
  }
  // The durable per-run receipt (research gap #2: the scan path left no trace beyond the run log).
  // $GITHUB_STEP_SUMMARY renders on the run's summary page; locally it just skips.
  if (process.env.GITHUB_STEP_SUMMARY && receipt.length) {
    writeFileSync(
      process.env.GITHUB_STEP_SUMMARY,
      `## Postmaster receipt\n\n${receipt.map((r) => `- ${r}`).join("\n")}\n`,
      { flag: "a" },
    );
  }
  if (receipt.length === 0) console.log("· nothing to do");
}

function executeOne(i) {
  if (i.kind === "noop") {
    console.log(`· nothing to do (${i.reason})`);
    return `noop — ${i.reason}`;
  }
  if (i.kind === "error") {
    console.error(`::error::${i.reason}`);
    process.exitCode = 1;
    return `❌ refused — ${i.reason}`;
  }
  if (i.kind === "open-issue") {
    ensureLabel(i.label);
    const url = sh("gh", [
      "issue",
      "create",
      "--title",
      i.title,
      "--body",
      i.body,
      "--label",
      i.label.name,
    ]);
    console.log(`▶ queued ${url}`);
    return `opened issue \`${i.title}\` → ${url}`;
  }
  if (i.kind === "comment") {
    sh("gh", ["issue", "comment", String(i.issueNumber), "--body", i.body]);
    console.log(`· commented on #${i.issueNumber}`);
    return `commented on #${i.issueNumber}`;
  }
  if (i.kind === "import-zip") {
    return importZip(i);
  }
  if (i.kind === "flip-handoff") {
    return flipHandoff(i);
  }
  if (i.kind === "release-claim") {
    const freed = releaseClaim(i.slug);
    console.log(
      `::notice::claim/${i.slug} ${freed ? "released" : "was not held"} (by @${i.actor})`,
    );
    return freed
      ? `🔓 released \`claim/${i.slug}\` — the next scan can pick it up (@${i.actor})`
      : `· no \`claim/${i.slug}\` to release — nothing was holding it`;
  }
  if (i.kind === "flag-stall") {
    if (i.issueNumber) {
      sh("gh", ["issue", "comment", String(i.issueNumber), "--body", i.body]);
      // The label is the audit's memory — it stops the next run re-flagging the same stall.
      ensureLabel(LABELS.stall);
      sh("gh", ["issue", "edit", String(i.issueNumber), "--add-label", LABELS.stall.name]);
    }
    console.log(`::warning::stall — ${i.slug ?? i.title} quiet ${i.quietDays}d`);
    return `⏱ stall flagged — \`${i.slug ?? i.title}\` quiet ${i.quietDays}d${i.issueNumber ? ` (commented on #${i.issueNumber})` : ""}`;
  }
  return `❓ unknown intent kind ${i.kind}`;
}

function ensureLabel(label) {
  // GitHub auto-creates a label the first time it is applied, but as default grey with no
  // description. Upsert so the repo self-provisions and nobody has to know it needed doing.
  const body = JSON.stringify(label);
  const base = `https://api.github.com/repos/${process.env.GITHUB_REPOSITORY}/labels`;
  const auth = [
    "-H",
    `Authorization: Bearer ${process.env.GH_TOKEN ?? ""}`,
    "-H",
    "Accept: application/vnd.github+json",
  ];
  try {
    sh("curl", ["-sS", "-X", "PATCH", ...auth, `${base}/${label.name}`, "-d", body]);
  } catch {
    try {
      sh("curl", ["-sS", "-X", "POST", ...auth, base, "-d", body]);
    } catch {
      /* a label that already exists is a harmless 422 */
    }
  }
}

/**
 * Open a PR, or degrade honestly. "Allow GitHub Actions to create and approve pull requests" is OFF
 * by default on every GitHub repo (docs/LESSONS.md 2026-08-17). When it is off, the branch is
 * already pushed and the work is already done — only this call fails. Never strand that behind a
 * raw error: name the cause, hand back the compare URL, and let the caller carry it into the
 * receipt and any originating issue.
 *
 * @returns {{ url: string|null, note: string|null }}
 */
function openPrOrExplain({ head, title, body }) {
  try {
    const url = sh("gh", [
      "pr",
      "create",
      "--base",
      "main",
      "--head",
      head,
      "--title",
      title,
      "--body",
      body,
    ]);
    try {
      sh("gh", ["pr", "merge", "--auto", "--squash", url]);
    } catch {
      /* auto-merge unavailable is non-fatal — the PR is open, which is the load-bearing part */
    }
    return { url, note: null };
  } catch (err) {
    const server = process.env.GITHUB_SERVER_URL ?? "https://github.com";
    const repo = process.env.GITHUB_REPOSITORY ?? "";
    const compare = `${server}/${repo}/compare/${head}?expand=1`;
    const refused = /not permitted to create or approve pull requests/.test(
      String(err.stderr || err.message),
    );
    const note = refused
      ? `⚠️ The branch is pushed and the work is safe, but this run could not open the PR: **GitHub Actions is not permitted to create or approve pull requests** in this repo.\n\n**Open it here:** ${compare}\n\n**To stop this recurring:** Settings → Actions → General → Workflow permissions → tick *Allow GitHub Actions to create and approve pull requests*.`
      : `⚠️ The branch is pushed and the work is safe, but opening the PR failed:\n\n\`\`\`\n${String(err.stderr || err.message).slice(0, 600)}\n\`\`\`\n\n**Open it manually:** ${compare}`;
    console.log(`::warning::PR not opened — ${compare}`);
    return { url: null, note };
  }
}

function importZip(intent) {
  // -L to follow the redirect; NO Authorization header (the pre-signed S3 URL carries its own and
  // refuses two auth mechanisms); a User-Agent because bare requests draw 403s. The signature
  // expires in ~5–10 minutes, so this must happen in the same run that read the issue body.
  sh("curl", [
    "-fsSL",
    "--retry",
    "3",
    "--retry-delay",
    "2",
    "-A",
    "skynet-postmaster/1.0",
    "-o",
    "/tmp/bundle.zip",
    intent.url,
  ]);
  const sha = sh("sha256sum", ["/tmp/bundle.zip"]).split(" ")[0];
  const bytes = sh("stat", ["-c%s", "/tmp/bundle.zip"]);

  sh("git", ["config", "user.name", "postmaster[bot]"]);
  sh("git", ["config", "user.email", "actions@github.com"]);
  let clean = true;
  try {
    sh("node", ["scripts/handoff-import.mjs", "/tmp/bundle.zip", "--slug", intent.slug], {
      stdio: "inherit",
    });
  } catch {
    clean = false; // a dirty contract still lands the branch — the receipt says so
  }

  const verdict = clean
    ? "Contract validated clean by `handoff-scan --validate`."
    : "⚠️ **The contract needs authoring** — the bundle's README does not yet satisfy `docs/handoffs/TEMPLATE.md`. It is safe at `draft` (inert), but a session must reshape it before this can build.";
  const prBody = [
    "## Summary",
    "",
    `- Imports the **${intent.slug}** design bundle into \`docs/handoffs/${intent.slug}/\`, dropped on #${intent.issueNumber} via the handoff inbox.`,
    `- ${verdict}`,
    "- Status: **draft — inert until Eric flips it to `ready`**.",
    "",
    FOOTER,
  ].join("\n");
  const pr = openPrOrExplain({
    head: `handoff/${intent.slug}`,
    title: `docs(handoff): ${intent.slug} design bundle`,
    body: prBody,
  });
  const prUrl = pr.url ?? "";

  sh("gh", [
    "issue",
    "comment",
    String(intent.issueNumber),
    "--body",
    [
      "**Receipt** — here is exactly what the machine received:",
      "",
      `- \`sha256\` \`${sha}\``,
      `- ${bytes} bytes`,
      `- slug: \`${intent.slug}\``,
      `- ${verdict}`,
      prUrl ? `- PR: ${prUrl}` : pr.note,
      "",
      FOOTER,
    ].join("\n"),
  ]);
  console.log(`▶ imported ${intent.slug} (${bytes} bytes, sha256 ${sha.slice(0, 12)}…)`);
  return `imported \`${intent.slug}\` (${bytes} bytes, sha256 \`${sha.slice(0, 12)}…\`)${prUrl ? ` → ${prUrl}` : " — ⚠️ PR not opened (compare URL in the issue comment)"}`;
}

function flipHandoff(intent) {
  const readme = `docs/handoffs/${intent.slug}/README.md`;
  const text = readFileSync(readme, "utf8").replace(/^(\*\*Status:\*\* *)draft/m, "$1ready");
  writeFileSync(readme, text);
  const branch = `flip/${intent.slug}`;
  sh("git", ["config", "user.name", intent.actor]);
  sh("git", ["config", "user.email", `${intent.actor}@users.noreply.github.com`]);
  sh("git", ["checkout", "-b", branch]);
  sh("git", ["add", "--", readme]);
  sh("git", [
    "commit",
    "-q",
    "-m",
    `docs(handoff): flip ${intent.slug} to ready`,
    "-m",
    `Authorized by @${intent.actor} via the postmaster's flip command. This is the build trigger.`,
  ]);
  sh("git", ["push", "-u", "origin", branch, "--force-with-lease"]);
  // A PR, never a direct push: a GITHUB_TOKEN push does not trigger other workflows, so pushing
  // straight to main would silently skip the detect sweep and no issue would ever open.
  const pr = openPrOrExplain({
    head: branch,
    title: `docs(handoff): flip ${intent.slug} to ready`,
    body: `**@${intent.actor} authorized \`${intent.slug}\` to build.**\n\nOn merge the detect sweep opens the \`[handoff] ${intent.slug}\` issue, a pickup layer claims it, and its first commit flips \`ready\` → \`executing\` — that flip is the lock.\n\n${FOOTER}`,
  });
  console.log(`▶ flipped ${intent.slug} → ready${pr.url ? `, PR ${pr.url}` : " (PR not opened)"}`);
  return pr.url
    ? `flipped \`${intent.slug}\` → ready (by @${intent.actor}) → ${pr.url}`
    : `flipped \`${intent.slug}\` → ready (by @${intent.actor}) — ⚠️ PR not opened\n\n${pr.note}`;
}

// ── entry point ───────────────────────────────────────────────────────────────
function main(argv) {
  const dry = argv.includes("--dry-run");
  const evIdx = argv.indexOf("--event");
  const eventFile = evIdx >= 0 ? argv[evIdx + 1] : process.env.GITHUB_EVENT_PATH;

  const raw = eventFile && existsSync(eventFile) ? JSON.parse(readFileSync(eventFile, "utf8")) : {};
  // A fixture may carry its own `deps`, so every routing branch is testable without a network.
  const fixtureDeps = raw.deps;
  const payload = raw.event ?? raw;

  const ctx = {
    eventName: raw.eventName ?? process.env.GITHUB_EVENT_NAME ?? "push",
    action: payload.action,
    payload,
    inputs: payload.inputs ?? raw.inputs ?? {},
    repo: process.env.GITHUB_REPOSITORY ?? "",
    actor: raw.actor ?? process.env.GITHUB_ACTOR ?? "unknown",
  };

  let deps = fixtureDeps ?? (dry ? {} : gatherDeps(ctx));
  // Fixture deps are plain JSON; a status MAP stands in for the on-disk lookup function.
  if (deps.handoffStatusMap) {
    const map = deps.handoffStatusMap;
    deps = { ...deps, handoffStatus: (slug) => map[slug] ?? null };
  }
  const auditMode = argv.includes("--audit") || ctx.inputs?.command === "audit";
  const intents = auditMode ? audit(fixtureDeps ?? gatherAuditDeps(Date.now())) : route(ctx, deps);

  if (dry) {
    console.log(JSON.stringify(intents, null, 2));
    return;
  }
  execute(intents);
}

if (import.meta.url === `file://${process.argv[1]}`) main(process.argv.slice(2));
