import type { TickerEntry } from "./types.js";

/** Retail, auto, travel and restaurant names. */
export const CONSUMER_DISCRETIONARY: readonly TickerEntry[] = [
  { symbol: "AMZN", name: "Amazon", sector: "Consumer Discretionary" },
  { symbol: "TSLA", name: "Tesla", sector: "Consumer Discretionary" },
  { symbol: "HD", name: "Home Depot", sector: "Consumer Discretionary" },
  { symbol: "MCD", name: "McDonald's", sector: "Consumer Discretionary" },
  { symbol: "NKE", name: "Nike", sector: "Consumer Discretionary" },
  { symbol: "LOW", name: "Lowe's", sector: "Consumer Discretionary" },
  { symbol: "SBUX", name: "Starbucks", sector: "Consumer Discretionary" },
  { symbol: "TJX", name: "TJX Companies", sector: "Consumer Discretionary" },
  { symbol: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary" },
  { symbol: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer Discretionary" },
  { symbol: "ABNB", name: "Airbnb", sector: "Consumer Discretionary" },
  { symbol: "MAR", name: "Marriott International", sector: "Consumer Discretionary" },
  { symbol: "GM", name: "General Motors", sector: "Consumer Discretionary" },
  { symbol: "F", name: "Ford Motor", sector: "Consumer Discretionary" },
  { symbol: "RCL", name: "Royal Caribbean", sector: "Consumer Discretionary" },
  { symbol: "CCL", name: "Carnival", sector: "Consumer Discretionary" },
  { symbol: "DHI", name: "D.R. Horton", sector: "Consumer Discretionary" },
  { symbol: "LEN", name: "Lennar", sector: "Consumer Discretionary" },
  { symbol: "ORLY", name: "O'Reilly Automotive", sector: "Consumer Discretionary" },
  { symbol: "AZO", name: "AutoZone", sector: "Consumer Discretionary" },
  { symbol: "YUM", name: "Yum! Brands", sector: "Consumer Discretionary" },
  { symbol: "DPZ", name: "Domino's Pizza", sector: "Consumer Discretionary" },
  { symbol: "ROST", name: "Ross Stores", sector: "Consumer Discretionary" },
  { symbol: "EBAY", name: "eBay", sector: "Consumer Discretionary" },
  { symbol: "ETSY", name: "Etsy", sector: "Consumer Discretionary" },
  { symbol: "NVR", name: "NVR", sector: "Consumer Discretionary" },
  { symbol: "PHM", name: "PulteGroup", sector: "Consumer Discretionary" },
  { symbol: "GRMN", name: "Garmin", sector: "Consumer Discretionary" },
  { symbol: "DECK", name: "Deckers Brands", sector: "Consumer Discretionary" },
  { symbol: "ULTA", name: "Ulta Beauty", sector: "Consumer Discretionary" },
];
