import type { TickerEntry } from "./types.js";

/** Big banks, card networks, insurers, exchanges and fintech names. */
export const FINANCIALS: readonly TickerEntry[] = [
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Financials" },
  { symbol: "BAC", name: "Bank of America", sector: "Financials" },
  { symbol: "WFC", name: "Wells Fargo", sector: "Financials" },
  { symbol: "C", name: "Citigroup", sector: "Financials" },
  { symbol: "GS", name: "Goldman Sachs", sector: "Financials" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financials" },
  { symbol: "SCHW", name: "Charles Schwab", sector: "Financials" },
  { symbol: "BLK", name: "BlackRock", sector: "Financials" },
  { symbol: "SPGI", name: "S&P Global", sector: "Financials" },
  { symbol: "AXP", name: "American Express", sector: "Financials" },
  { symbol: "V", name: "Visa", sector: "Financials" },
  { symbol: "MA", name: "Mastercard", sector: "Financials" },
  { symbol: "PYPL", name: "PayPal", sector: "Financials" },
  { symbol: "COF", name: "Capital One", sector: "Financials" },
  { symbol: "USB", name: "U.S. Bancorp", sector: "Financials" },
  { symbol: "PNC", name: "PNC Financial Services", sector: "Financials" },
  { symbol: "TFC", name: "Truist Financial", sector: "Financials" },
  { symbol: "BK", name: "Bank of New York Mellon", sector: "Financials" },
  { symbol: "CB", name: "Chubb", sector: "Financials" },
  { symbol: "MMC", name: "Marsh & McLennan", sector: "Financials" },
  { symbol: "AIG", name: "AIG", sector: "Financials" },
  { symbol: "MET", name: "MetLife", sector: "Financials" },
  { symbol: "PRU", name: "Prudential Financial", sector: "Financials" },
  { symbol: "AFL", name: "Aflac", sector: "Financials" },
  { symbol: "TRV", name: "Travelers", sector: "Financials" },
  { symbol: "ICE", name: "Intercontinental Exchange", sector: "Financials" },
  { symbol: "CME", name: "CME Group", sector: "Financials" },
  { symbol: "COIN", name: "Coinbase", sector: "Financials" },
  { symbol: "SOFI", name: "SoFi Technologies", sector: "Financials" },
  { symbol: "ALLY", name: "Ally Financial", sector: "Financials" },
  { symbol: "FI", name: "Fiserv", sector: "Financials" },
  { symbol: "AON", name: "Aon", sector: "Financials" },
  { symbol: "ALL", name: "Allstate", sector: "Financials" },
  { symbol: "PGR", name: "Progressive", sector: "Financials" },
  { symbol: "DFS", name: "Discover Financial Services", sector: "Financials" },
];
