import type { TickerEntry } from "./types.js";

/** Large/mid-cap pharma, biotech, med-tech and managed-care names. */
export const HEALTHCARE: readonly TickerEntry[] = [
  { symbol: "UNH", name: "UnitedHealth Group", sector: "Healthcare" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { symbol: "LLY", name: "Eli Lilly", sector: "Healthcare" },
  { symbol: "ABBV", name: "AbbVie", sector: "Healthcare" },
  { symbol: "MRK", name: "Merck", sector: "Healthcare" },
  { symbol: "PFE", name: "Pfizer", sector: "Healthcare" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
  { symbol: "DHR", name: "Danaher", sector: "Healthcare" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare" },
  { symbol: "AMGN", name: "Amgen", sector: "Healthcare" },
  { symbol: "GILD", name: "Gilead Sciences", sector: "Healthcare" },
  { symbol: "CVS", name: "CVS Health", sector: "Healthcare" },
  { symbol: "CI", name: "Cigna", sector: "Healthcare" },
  { symbol: "ELV", name: "Elevance Health", sector: "Healthcare" },
  { symbol: "MDT", name: "Medtronic", sector: "Healthcare" },
  { symbol: "ISRG", name: "Intuitive Surgical", sector: "Healthcare" },
  { symbol: "SYK", name: "Stryker", sector: "Healthcare" },
  { symbol: "BSX", name: "Boston Scientific", sector: "Healthcare" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare" },
  { symbol: "ZTS", name: "Zoetis", sector: "Healthcare" },
  { symbol: "HCA", name: "HCA Healthcare", sector: "Healthcare" },
  { symbol: "BDX", name: "Becton Dickinson", sector: "Healthcare" },
  { symbol: "MRNA", name: "Moderna", sector: "Healthcare" },
  { symbol: "BIIB", name: "Biogen", sector: "Healthcare" },
  { symbol: "HUM", name: "Humana", sector: "Healthcare" },
  { symbol: "IDXX", name: "IDEXX Laboratories", sector: "Healthcare" },
  { symbol: "EW", name: "Edwards Lifesciences", sector: "Healthcare" },
  { symbol: "DXCM", name: "DexCom", sector: "Healthcare" },
  { symbol: "CNC", name: "Centene", sector: "Healthcare" },
  { symbol: "MCK", name: "McKesson", sector: "Healthcare" },
  { symbol: "COR", name: "Cencora", sector: "Healthcare" },
  { symbol: "A", name: "Agilent Technologies", sector: "Healthcare" },
];
