import type { TickerEntry } from "./types.js";

/** Large/mid-cap technology and semiconductor names. */
export const TECHNOLOGY: readonly TickerEntry[] = [
  { symbol: "AAPL", name: "Apple", sector: "Technology" },
  { symbol: "MSFT", name: "Microsoft", sector: "Technology" },
  { symbol: "NVDA", name: "Nvidia", sector: "Technology" },
  { symbol: "AVGO", name: "Broadcom", sector: "Technology" },
  { symbol: "ORCL", name: "Oracle", sector: "Technology" },
  { symbol: "CRM", name: "Salesforce", sector: "Technology" },
  { symbol: "ADBE", name: "Adobe", sector: "Technology" },
  { symbol: "CSCO", name: "Cisco", sector: "Technology" },
  { symbol: "ACN", name: "Accenture", sector: "Technology" },
  { symbol: "IBM", name: "IBM", sector: "Technology" },
  { symbol: "INTC", name: "Intel", sector: "Technology" },
  { symbol: "AMD", name: "AMD", sector: "Technology" },
  { symbol: "QCOM", name: "Qualcomm", sector: "Technology" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Technology" },
  { symbol: "INTU", name: "Intuit", sector: "Technology" },
  { symbol: "NOW", name: "ServiceNow", sector: "Technology" },
  { symbol: "AMAT", name: "Applied Materials", sector: "Technology" },
  { symbol: "MU", name: "Micron", sector: "Technology" },
  { symbol: "LRCX", name: "Lam Research", sector: "Technology" },
  { symbol: "ADI", name: "Analog Devices", sector: "Technology" },
  { symbol: "KLAC", name: "KLA", sector: "Technology" },
  { symbol: "SNPS", name: "Synopsys", sector: "Technology" },
  { symbol: "CDNS", name: "Cadence Design Systems", sector: "Technology" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Technology" },
  { symbol: "CRWD", name: "CrowdStrike", sector: "Technology" },
  { symbol: "FTNT", name: "Fortinet", sector: "Technology" },
  { symbol: "MRVL", name: "Marvell Technology", sector: "Technology" },
  { symbol: "ANSS", name: "Ansys", sector: "Technology" },
  { symbol: "ADSK", name: "Autodesk", sector: "Technology" },
  { symbol: "WDAY", name: "Workday", sector: "Technology" },
  { symbol: "TEAM", name: "Atlassian", sector: "Technology" },
  { symbol: "ZS", name: "Zscaler", sector: "Technology" },
  { symbol: "NET", name: "Cloudflare", sector: "Technology" },
  { symbol: "DDOG", name: "Datadog", sector: "Technology" },
  { symbol: "SNOW", name: "Snowflake", sector: "Technology" },
  { symbol: "PLTR", name: "Palantir", sector: "Technology" },
  { symbol: "SHOP", name: "Shopify", sector: "Technology" },
  { symbol: "UBER", name: "Uber", sector: "Technology" },
  { symbol: "DELL", name: "Dell Technologies", sector: "Technology" },
  { symbol: "HPQ", name: "HP", sector: "Technology" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology" },
  { symbol: "STX", name: "Seagate Technology", sector: "Technology" },
  { symbol: "WDC", name: "Western Digital", sector: "Technology" },
  { symbol: "SMCI", name: "Super Micro Computer", sector: "Technology" },
  { symbol: "ARM", name: "Arm Holdings", sector: "Technology" },
  { symbol: "CRWV", name: "CoreWeave", sector: "Technology" },
  { symbol: "NXPI", name: "NXP Semiconductors", sector: "Technology" },
  { symbol: "ON", name: "ON Semiconductor", sector: "Technology" },
  { symbol: "SWKS", name: "Skyworks Solutions", sector: "Technology" },
  { symbol: "MCHP", name: "Microchip Technology", sector: "Technology" },
  { symbol: "TSM", name: "Taiwan Semiconductor", sector: "Technology" },
  { symbol: "ASML", name: "ASML Holding", sector: "Technology" },
  { symbol: "GEN", name: "Gen Digital", sector: "Technology" },
  { symbol: "AKAM", name: "Akamai Technologies", sector: "Technology" },
  { symbol: "JNPR", name: "Juniper Networks", sector: "Technology" },
  { symbol: "TER", name: "Teradyne", sector: "Technology" },
  { symbol: "KEYS", name: "Keysight Technologies", sector: "Technology" },
];
