import { describe, expect, it } from "@rstest/core";
import {
  boardStatus,
  csv,
  findDuplicates,
  followUps,
  matches,
  nextLabels,
  parseArgs,
  row,
  titleWords,
  withFooter,
} from "../../scripts/issues.mjs";

// The issue CLI's pure core: the parts that decide whether a filing is refused, what the board
// column reads, and which labels an edit leaves — proven without calling GitHub.
describe("issues cli: parseArgs", () => {
  it("splits the command, positionals, value flags and boolean flags", () => {
    const out = parseArgs(["update", "42", "--add", "needs-eric,bug", "--reopen"]);
    expect(out).toEqual({
      cmd: "update",
      positional: ["42"],
      flags: { add: "needs-eric,bug", reopen: true },
    });
  });
});

describe("issues cli: findDuplicates", () => {
  const open = [
    { number: 1, title: "Add Dependabot secrets so dependency PRs get reviewed and merged" },
    { number: 2, title: "Freeze the research screenshot fixture" },
  ];

  it("flags an open issue asking the same thing in different punctuation", () => {
    const hits = findDuplicates(
      "Add dependabot secrets — so dependency PRs get reviewed & merged",
      open,
    );
    expect(hits.map((h) => h.number)).toEqual([1]);
  });

  it("lets a merely related title through", () => {
    expect(findDuplicates("Stop running route on Dependabot PRs", open)).toEqual([]);
  });

  it("never matches an empty or all-stopword title", () => {
    expect(findDuplicates("a b", open)).toEqual([]);
    expect(titleWords("a b").size).toBe(0);
  });
});

describe("issues cli: board status follows labels", () => {
  const CALLOUT = "> [!IMPORTANT]\n> **Needs from you**\n> 1. Pick A or B?";

  it("reads needs-eric as Blocked, ready as Ready, closed as Done", () => {
    expect(
      boardStatus({ title: "x", state: "open", labels: [{ name: "needs-eric" }], body: CALLOUT }),
    ).toBe("Blocked");
    expect(boardStatus({ title: "x", state: "open", labels: ["ready"] })).toBe("Ready");
    expect(boardStatus({ title: "x", state: "closed", labels: ["needs-eric"] })).toBe("Done");
    expect(boardStatus({ title: "x", state: "open", labels: [] })).toBe("Backlog");
  });

  // #3913 slice 2: the board keeps an unstated ask out of Blocked until the callout is written.
  it("keeps a needs-eric issue with no callout out of Blocked, unless Eric filed it", () => {
    const labels = [{ name: "needs-eric" }];
    expect(boardStatus({ title: "x", state: "open", labels, body: "no ask" })).toBe("Backlog");
    expect(
      boardStatus({ title: "x", state: "open", labels, body: "", user: { login: "ejclark" } }),
    ).toBe("Blocked");
  });

  it("prints one scan-able row per issue", () => {
    expect(row({ number: 7, title: "T", state: "open", labels: [{ name: "needs-info" }] })).toBe(
      "#7 [Blocked] T  (needs-info)",
    );
  });
});

describe("issues cli: edits", () => {
  it("adds and removes labels without duplicating", () => {
    expect(nextLabels(["a", "b"], ["b", "c"], ["a"])).toEqual(["b", "c"]);
  });

  it("parses comma lists, dropping blanks", () => {
    expect(csv(" a, ,b ")).toEqual(["a", "b"]);
    expect(csv(undefined)).toEqual([]);
  });

  it("appends the attribution footer once", () => {
    const once = withFooter("body");
    expect(once).toContain("Generated by [Claude Code]");
    expect(withFooter(once)).toBe(once);
  });

  it("matches every word across title and body, and filters by label", () => {
    const issue = {
      title: "Add Dependabot secrets",
      body: "dep-warden login",
      labels: ["needs-eric"],
    };
    expect(matches(issue, "dependabot login")).toBe(true);
    expect(matches(issue, "dependabot deploy")).toBe(false);
    expect(matches(issue, "", { label: "needs-eric" })).toBe(true);
    expect(matches(issue, "", { label: "ready" })).toBe(false);
  });
});

describe("issues cli: followUps (slices as sub-issues)", () => {
  const child = { id: 9001, number: 42 };

  it("links to the parent, adds each blocker, then closes a shipped slice — in that order", () => {
    const ops = followUps({ child, parentNumber: 7, blockers: [{ id: 11 }], closed: true });
    expect(ops.map((o) => `${o.method} ${o.path}`)).toEqual([
      "POST issues/7/sub_issues",
      "POST issues/42/dependencies/blocked_by",
      "PATCH issues/42",
    ]);
    expect(ops[0]?.payload).toEqual({ sub_issue_id: 9001 });
    expect(ops[1]?.payload).toEqual({ issue_id: 11 });
    expect(ops[2]?.payload).toEqual({ state: "closed", state_reason: "completed" });
  });

  it("writes nothing for a plain filing", () => {
    expect(followUps({ child })).toEqual([]);
  });
});
