import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "@rstest/core";
import {
  CLAUDE_READY_LINE,
  isClaudeComment,
  isClaudeReadyLine,
  isReadySignal,
} from "../../scripts/moneypenny/plan-claim.mjs";
import { quote } from "../../scripts/steer/filings.mjs";
import { parseSteerMarker } from "../../scripts/steer/model.mjs";
import {
  anchorDecision,
  commandsFor,
  DEFAULT_APPLIED,
  DONE_TRIGGER,
  type ReadbackAction,
  readback,
} from "../../scripts/steer/readback.mjs";
import { fixture, ROUND } from "./steer-fixture";

/** The capsule gate an issue body must pass before `issues.mjs create` files it (the CLI form,
 *  as tests/arch/issue-lint.spec.ts drives it). */
const lintProblems = (title: string, body: string): string[] => {
  try {
    const out = execFileSync(
      "node",
      ["scripts/issue-lint.mjs", "--stdin", "--json", "--title", title],
      {
        input: body,
        encoding: "utf8",
      },
    );
    return JSON.parse(out).problems;
  } catch (error) {
    return JSON.parse(
      (error as { stdout?: Buffer }).stdout?.toString() || '{"problems":["no output"]}',
    ).problems;
  }
};
type NewIssue = Extract<ReadbackAction, { kind: "issue" }>;

// #5056 criterion 7, and the red-team findings that shaped it: a skipped real decision waits for
// the next page, only a reversible approval takes its default, and nothing the read-back posts as
// ejclark can ever read as his ready-flip.
const FOOTER = "---\n_Generated by [Claude Code](https://claude.ai/code)_";
const at = (path: string) => `tp/${ROUND}/${path}`;
const NOTE = "ship it\n\nkeep the row, lose the card";

const tp = fixture();
const records: Record<string, unknown> = {
  [`tp/${ROUND}`]: {
    openedAt: "2026-10-10T21:30:00Z",
    doneAt: "2026-10-10T21:50:00Z",
    taps: [0, 60_000],
  },
  // 2224 fork: a note only. 4100 approve: skipped (its default applies). 4200 approve on a plan.
  [at("decisions/2224")]: { note: "Shape 5, but only after the Council ships" },
  [at("decisions/4200")]: { verdict: "approve", note: NOTE },
  // 4300 held PR: a note — still only his click merges it. 5037-q2: skipped.
  [at("decisions/4300")]: { note: "waiting on the deploy check" },
  [at("decisions/5037-q1")]: { pick: "A", react: { B: "more", C: "not" }, note: NOTE },
  [at("queue/4437")]: { verdict: "veto", note: "not this week" },
  [at("queue/4241")]: { verdict: "bump" },
  [at("reel/5054")]: { verdict: "revisit", note: "the squares still look tiny on my phone" },
};
const plan = readback(tp, records);
const comments = plan.actions.filter((a) => a.kind === "comment");
const commentOn = (n: number) => comments.filter((a) => a.issue === n);
const labelsOn = (n: number) => plan.actions.find((a) => a.kind === "labels" && a.issue === n);
const newIssues = plan.actions.filter((a): a is NewIssue => a.kind === "issue");

describe("a skipped item", () => {
  it("takes its default only when it is a reversible approval, and says it was the default", () => {
    expect(plan.defaults.map((d) => d.issue)).toEqual([4100]);
    const [c] = commentOn(4100);
    expect(c?.body).toContain(`${DEFAULT_APPLIED}: replies on a Council line`);
    expect(labelsOn(4100)).toMatchObject({ remove: ["needs-eric"] });
  });

  it("rolls over untouched when it is a fork, a design round or a held PR", () => {
    const skipped = readback(tp, {});
    const kinds = new Map(skipped.rollover.map((r) => [r.key, r.kind]));
    expect(kinds.get("2224")).toBe("fork");
    expect(kinds.get("5037-q2")).toBe("design");
    expect(kinds.get("4300")).toBe("approve");
    const touched = new Set(skipped.actions.map((a) => a.issue));
    for (const n of [2224, 5037, 4300]) expect(touched.has(n)).toBe(false);
    // The two reversible approvals took their stated defaults instead; neither is a ready-flip.
    expect(skipped.defaults.map((d) => d.issue)).toEqual([4100, 4200]);
    expect(skipped.actions.some((a) => a.kind === "comment" && isClaudeReadyLine(a.body))).toBe(
      false,
    );
  });

  it("keeps a held PR open even when Eric wrote on it — only his click merges", () => {
    expect(plan.rollover.find((r) => r.key === "4300")?.why).toMatch(/irreversible/);
    expect(labelsOn(4300)).toBeUndefined();
    expect(commentOn(4300)[0]?.body).toContain("> waiting on the deploy check");
  });

  it("moves no label on “Not now” — on a ready plan, taking needs-eric off would start a build", () => {
    const notNow = readback(tp, { [at("decisions/2224")]: { verdict: "not" } });
    expect(notNow.actions.some((a) => a.kind === "labels" && a.issue === 2224)).toBe(false);
    expect(notNow.rollover.map((r) => r.key)).toContain("2224");
    expect(notNow.followUps).toContainEqual(expect.objectContaining({ kind: "not", issue: 2224 }));
  });

  it("settles a fork on “my note settles it” only when there is a note to settle it", () => {
    const empty = readback(tp, { [at("decisions/2224")]: { verdict: "build", note: "  " } });
    expect(empty.actions.some((a) => a.kind === "labels" && a.issue === 2224)).toBe(false);
    expect(empty.rollover.map((r) => r.key)).toContain("2224");
    const said = readback(tp, { [at("decisions/2224")]: { verdict: "build", note: "Shape 5" } });
    expect(said.actions).toContainEqual(
      expect.objectContaining({ kind: "labels", issue: 2224, remove: ["needs-eric"] }),
    );
  });

  it("follows up a design question answered with a note alone", () => {
    const noted = readback(tp, { [at("decisions/5037-q2")]: { note: "neither, try a sheet" } });
    expect(noted.followUps).toContainEqual(
      expect.objectContaining({ kind: "read-note", key: "5037-q2" }),
    );
  });

  it("moves no label on a note alone; the note is quoted and the item stays his", () => {
    expect(labelsOn(2224)).toBeUndefined();
    expect(plan.followUps).toContainEqual(
      expect.objectContaining({ kind: "read-note", issue: 2224 }),
    );
  });
});

describe("every comment the read-back posts as ejclark", () => {
  it("ends with the lane footer", () => {
    expect(comments.length).toBeGreaterThan(0);
    for (const c of comments) {
      expect(c.body.endsWith(FOOTER)).toBe(true);
      expect(isClaudeComment(c.body)).toBe(true);
    }
  });

  it("never reads as a ready-flip — except the one Approve on a plan, led by the exact line", () => {
    const flips = comments.filter((c) => isClaudeReadyLine(c.body));
    expect(flips).toHaveLength(1);
    expect(flips[0]?.issue).toBe(4200);
    expect(flips[0]?.body.split("\n")[0]).toBe(CLAUDE_READY_LINE);
    // Without the footer, the quoted note alone would have flipped the plan.
    expect(isReadySignal(NOTE.split("\n")[0])).toBe(true);
  });

  it("quotes Eric's note word for word, blank lines included", () => {
    expect(quote(NOTE)).toBe("> ship it\n>\n> keep the row, lose the card");
    expect(commentOn(5037)[0]?.body).toContain(quote(NOTE));
  });
});

describe("routing through the existing doors", () => {
  it("files each Build on a design option as a feedback issue that lints clean and remembers why", () => {
    const build = newIssues.find((a) => a.why === "Build on 5037-q1");
    expect(build?.labels).toEqual(["feedback", "ready"]);
    expect(lintProblems(build?.title ?? "", build?.body ?? "")).toEqual([]);
    expect(parseSteerMarker(build?.body)).toEqual({
      round: ROUND,
      key: "5037-q1",
      note: "ship it",
    });
  });

  it("records the design round's More/Not marks for the next round", () => {
    expect(commentOn(5037)[0]?.body).toMatch(/More of: B \("A sheet from the row"\)/);
    expect(commentOn(5037)[0]?.body).toMatch(/- Not: C/);
    expect(plan.followUps).toContainEqual(
      expect.objectContaining({ kind: "next-round", issue: 5037 }),
    );
  });

  it("vetoes by taking ready off, bumps with P1, and files Revisit as feedback", () => {
    expect(labelsOn(4437)).toMatchObject({ remove: ["ready"], add: [] });
    expect(labelsOn(4241)).toMatchObject({ add: ["P1"] });
    const revisit = newIssues.find((a) => a.why === "Revisit on #5054");
    expect(revisit?.labels).toEqual(["feedback"]);
    expect(lintProblems(revisit?.title ?? "", revisit?.body ?? "")).toEqual([]);
  });

  it("reports the page's Done and active minutes", () => {
    expect(plan).toMatchObject({ round: ROUND, done: true, activeMinutes: 1 });
  });
});

describe("the commands a session runs", () => {
  it("writes each body to a file and posts it over REST, labels riding the same call", () => {
    const dir = mkdtempSync(join(tmpdir(), "steer-readback-"));
    try {
      const cmds = commandsFor(plan, dir);
      const on4437 = cmds.find((c) => c[3] === "4437");
      expect(on4437?.slice(0, 4)).toEqual(["node", "scripts/issues.mjs", "update", "4437"]);
      expect(on4437).toContain("--remove");
      const file = on4437?.[on4437.indexOf("--comment-file") + 1] ?? "";
      expect(readFileSync(file, "utf8")).toContain("> not this week");
      expect(cmds.filter((c) => c[2] === "create")).toHaveLength(2);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

// #5056, Eric 2026-10-10: comments he sends to Claude on the page count. An automatic reply had
// told him "a comment here won't show up in the read-back"; now each one is quoted word for word
// beside his taps, on the issue the decision came from.
describe("Eric's comments on the page", () => {
  const said = [
    {
      anchorKey: "d-5037-q1-B",
      text: "this one, but\n\nwith the row kept",
      at: "2026-10-10T21:41:00Z",
    },
    { anchorKey: "#d-5037-q1", text: "progressive reveal everywhere", at: "2026-10-10T21:40:00Z" },
    {
      anchorKey: "4100",
      text: "ready — take slice 1 per the state block",
      at: "2026-10-10T21:42:00Z",
    },
    { anchorKey: "queue", text: "the queue feels long", at: "2026-10-10T21:43:00Z" },
    { anchorKey: "d-2224", text: "   ", at: "2026-10-10T21:44:00Z" },
    // The page's own Done press (#5135): sent to Claude to start this read-back, not his words.
    {
      anchorKey: "div.bar",
      text: `${DONE_TRIGGER} ${ROUND}: 4 of 5 answered. Read it back.`,
      at: "2026-10-10T21:45:00Z",
    },
  ];
  const withComments = readback(tp, records, said);
  const on = (n: number) =>
    withComments.actions
      .filter((a) => a.kind === "comment")
      .filter((a) => a.issue === n)
      .map((a) => a.body);

  it("quotes each one word for word under its decision, oldest first, naming the option it sits on", () => {
    const body = on(5037)[0] ?? "";
    const block = [
      "Eric's comments on the page:",
      quote("progressive reveal everywhere"),
      "On option B:",
      quote("this one, but\n\nwith the row kept"),
    ].join("\n\n");
    expect(body).toContain(block);
    // Inside question 1's part, after its taps and note — never under another question.
    expect(body.indexOf(block)).toBeGreaterThan(body.indexOf("**Q1 · "));
    expect(withComments.followUps).toContainEqual(
      expect.objectContaining({ kind: "read-comment", key: "5037-q1" }),
    );
  });

  it("keeps a decision he commented on without a tap open: quoted, no default, no label", () => {
    expect(withComments.defaults.map((d) => d.issue)).not.toContain(4100);
    expect(withComments.actions.some((a) => a.kind === "labels" && a.issue === 4100)).toBe(false);
    expect(withComments.rollover.find((r) => r.key === "4100")?.why).toMatch(/commented/);
    expect(on(4100)[0]).toContain("> ready — take slice 1 per the state block");
  });

  it("never lets a quoted comment read as his ready-flip: footed, led by the bold header", () => {
    expect(on(4100)).toHaveLength(1);
    for (const body of on(4100)) {
      expect(body.endsWith(FOOTER)).toBe(true);
      expect(isClaudeReadyLine(body)).toBe(false);
      expect(body.split("\n")[0]).toMatch(/^\*\*Answered on the decisions page/);
    }
  });

  it("hands back a comment that sits on no shown decision, and drops an empty one", () => {
    expect(withComments.unplacedComments.map((c) => c.anchorKey)).toEqual(["queue"]);
    expect(on(2224)[0]).not.toContain("Eric's comments on the page");
  });

  it("drops the Done press the page sent to start the read-back: it is a trigger, not his words", () => {
    expect(DONE_TRIGGER).toBe("Done with steering round");
    const all = withComments.actions.map((a) => ("body" in a ? a.body : "")).join("\n");
    expect(all).not.toContain(DONE_TRIGGER);
    const onADecision = readback(tp, records, [
      { anchorKey: "d-2224", text: `${DONE_TRIGGER} ${ROUND}: 1 of 5 answered. Read it back.` },
    ]);
    expect(onADecision).toEqual(plan);
  });

  it("leaves the plan exactly as before when there are no comments", () => {
    expect(plan.unplacedComments).toEqual([]);
    expect(readback(tp, records, [])).toEqual(plan);
  });

  it("maps an anchor to the longest matching key, so 5037 never claims 5037-q1's comments", () => {
    const ds = [
      { key: "5037", options: [] },
      { key: "5037-q1", options: [{ key: "A" }] },
    ] as unknown as Parameters<typeof anchorDecision>[1];
    expect(anchorDecision("d-5037-q1-A", ds)).toMatchObject({ d: { key: "5037-q1" }, opt: "A" });
    expect(anchorDecision("d-5037", ds)).toMatchObject({ d: { key: "5037" }, opt: null });
    expect(anchorDecision("d-503", ds)).toBeNull();
  });

  it("reads them from --comments on the command line, and refuses a file that is not a list", () => {
    const dir = mkdtempSync(join(tmpdir(), "steer-comments-"));
    const run = (comments: string) =>
      execFileSync(
        "node",
        [
          "scripts/steer/readback.mjs",
          ...["--tp", join(dir, "tp.json"), "--records", join(dir, "records.json")],
          ...["--comments", join(dir, comments)],
        ],
        { encoding: "utf8", stdio: "pipe" },
      );
    try {
      writeFileSync(join(dir, "tp.json"), JSON.stringify(tp));
      writeFileSync(join(dir, "records.json"), JSON.stringify(records));
      writeFileSync(join(dir, "comments.json"), JSON.stringify(said));
      writeFileSync(join(dir, "bad.json"), JSON.stringify({ text: "not a list" }));
      const cli = JSON.parse(run("comments.json")) as { actions: ReadbackAction[] };
      const c = cli.actions.filter((a) => a.kind === "comment").find((a) => a.issue === 5037);
      expect(c?.body).toContain("> progressive reveal everywhere");
      expect(() => run("bad.json")).toThrow();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
